// Data for the Website Examples page — from Marketing - Website Examples.dc.html.
//
// Note: the prototype's `url` field for every example was copy-pasted as
// "https://celestialdelicacies.com" (a single placeholder), even though
// each card's own `domain` field is distinct — the modal it feeds always
// opened the same one site regardless of which card was clicked. Real
// domains generate `https://{domain}` instead, since that's clearly the
// intent (the modal header already displays that same domain) rather
// than reproducing what reads as a copy-paste bug, not a copy decision.

export type ExampleSite = {
  name: string; brand: string; domain: string; category: string; cat: string
  nav: string[]; cta: string; ctaBg: string; ctaInk: string
  heroLine: string; heroBlurb: string; result: string; tint: string
  // Real proof screenshot (Google search/Maps listing) pulled from
  // matjarx.com's WordPress media library — same file and alt text
  // already indexed by Google, not a new asset.
  proofImage?: { src: string; alt: string; width: number; height: number }
}

export const EXAMPLES: ExampleSite[] = [
  { name: 'Bin Adam Textile', brand: 'BIN ADAM', domain: 'binadamtextiles.com', category: 'Textiles', cat: 'Textiles',
    nav: ['Rates', 'Bulk orders', 'About'], cta: 'Get A Quote', ctaBg: '#F4F2AE', ctaInk: '#16210B',
    heroLine: 'Fabric by the bale, priced clearly.', heroBlurb: 'Faisalabad wholesaler with live rate tables and bulk enquiry forms.',
    result: '#1 on Google', tint: 'linear-gradient(150deg, #003366, #0A2647)' },
  { name: 'Elegance Embroidery', brand: 'ELEGANCE', domain: 'elegance-handicraft.matjarpk.com', category: 'Boutiques', cat: 'Boutiques',
    nav: ['Shop', 'Collections', 'Fabric guide'], cta: 'Order Now', ctaBg: '#F4F2AE', ctaInk: '#16210B',
    heroLine: 'Hand-stitched, made to be seen.', heroBlurb: 'Chikankari and ajrak work, delivered nationwide with cash on delivery.',
    result: 'Online in 6 days', tint: 'linear-gradient(150deg, #7A2E6B, #2A0F24)' },
  { name: 'Zulfay Hair', brand: 'ZULFAY', domain: 'zulfayhair.com', category: 'Salons', cat: 'Salons',
    nav: ['Stylists', 'Price list', 'Gallery'], cta: 'Book Now', ctaBg: '#E8B4C8', ctaInk: '#2A0F1A',
    heroLine: 'Your chair is ready.', heroBlurb: 'Multi-seat booking across three branches, synced to every stylist\'s calendar.',
    result: '1,520 messages', tint: 'linear-gradient(150deg, #A0522D, #3E1B0C)',
    proofImage: { src: '/services/zulfay-map-listing.webp', alt: 'Zulfay Hair Google search listing featuring the Zulfay logo, 4.8-star rating, salon information, and website button.', width: 1552, height: 1013 } },
  { name: 'CapActix Offshore', brand: 'CAPACTIX', domain: 'capactix.com', category: 'Accounting', cat: 'Accounting',
    nav: ['Services', 'Pricing', 'Blog'], cta: 'Request Call', ctaBg: '#C4262E', ctaInk: '#FFFFFF',
    heroLine: 'Numbers that matter.', heroBlurb: 'We turn your financial data into reporting you can actually act on.',
    result: '550+ reviews', tint: 'linear-gradient(150deg, #10265A, #050F2A)' },
  { name: 'Eebeel Home', brand: 'EEBEEL', domain: 'eebeel.com', category: 'E-commerce', cat: 'E-commerce',
    nav: ['Shop', 'Track order', 'Support'], cta: 'Order Now', ctaBg: '#F4F2AE', ctaInk: '#16210B',
    heroLine: 'Everything for the home.', heroBlurb: '400+ products with JazzCash, Easypaisa and cash-on-delivery checkout.',
    result: '2,000+ leads', tint: 'linear-gradient(150deg, #6A2C8E, #2A0F3A)',
    proofImage: { src: '/services/eebeel-map-listing.webp', alt: 'eebeel Google search listing featuring the eebeel logo, 4.8-star rating, beauty and personal care information, and website button.', width: 1552, height: 1013 } },
  { name: 'Askari Estates', brand: 'ASKARI ESTATES', domain: 'askariestateco.com', category: 'Real Estate', cat: 'Real Estate',
    nav: ['Listings', 'Plots', 'Contact'], cta: 'View Listings', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Find your next address in Islamabad.', heroBlurb: 'Live plot and house listings with price, size and location filters, updated daily.',
    result: '3× more enquiries', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'IronCore Fitness', brand: 'IRONCORE', domain: 'ironcorefitness.net', category: 'Gyms And Fitness', cat: 'Gyms And Fitness',
    nav: ['Memberships', 'Classes', 'Trainers'], cta: 'Join Now', ctaBg: '#D6E63A', ctaInk: '#1A2004',
    heroLine: 'Train like it matters.', heroBlurb: 'Membership sign-up and class booking online, with trainer profiles and a live timetable.',
    result: '200+ sign-ups online', tint: 'linear-gradient(150deg, #23291A, #0A0D06)' },
  { name: 'Chaudhry & Fitzgerald Law', brand: 'C&F LAW', domain: 'chaudhrylaw.com', category: 'Legal Services', cat: 'Legal Services',
    nav: ['Practice areas', 'Our team', 'Consult'], cta: 'Book A Consult', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Advice you can act on.', heroBlurb: 'Corporate, property and family law in Lahore, with a confidential online consultation form.',
    result: 'Fully booked most weeks', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Noor & Co. Events', brand: 'NOOR & CO.', domain: 'noornco.com', category: 'Wedding And Caterers', cat: 'Wedding And Caterers',
    nav: ['Packages', 'Gallery', 'Enquire'], cta: 'Check Availability', ctaBg: '#E8B4C8', ctaInk: '#2A0F1A',
    heroLine: 'Your day, planned properly.', heroBlurb: 'Wedding planning and catering packages for Karachi, with a real-time date-availability form.',
    result: 'Booked out 8 months ahead', tint: 'linear-gradient(150deg, #6E1B4A, #240818)' },
  { name: 'Speedway Auto Care', brand: 'SPEEDWAY', domain: 'speedwayautotrading.com', category: 'Trades', cat: 'Trades',
    nav: ['Services', 'Book a slot', 'Reviews'], cta: 'Book A Slot', ctaBg: '#C4262E', ctaInk: '#FFFFFF',
    heroLine: 'Your car, back on the road fast.', heroBlurb: 'Online booking for servicing and repairs across two Rawalpindi branches, synced to one calendar.',
    result: 'Bookings up 2.5×', tint: 'linear-gradient(150deg, #1A1A1A, #050505)' },
  { name: 'Margalla Builders', brand: 'MARGALLA', domain: 'margallaeliteconstruction.com', category: 'Construction', cat: 'Construction',
    nav: ['Projects', 'Services', 'Get A Quote'], cta: 'Get A Quote', ctaBg: '#E9A94F', ctaInk: '#2A1608',
    heroLine: 'Built to last, on schedule.', heroBlurb: 'Islamabad contractor with a project gallery and a quote-request form routed to the right site manager.',
    result: '40+ projects showcased', tint: 'linear-gradient(150deg, #4A3B1A, #1A1506)' },
  { name: 'Patrick Accounting', brand: 'PATRICK', domain: 'patrickaccounting.com', category: 'Accounting', cat: 'Accounting',
    nav: ['Services', 'Pricing', 'About'], cta: 'Let\'s Chat', ctaBg: '#2E6F4E', ctaInk: '#FFFFFF',
    heroLine: 'Books handled. Business grown.', heroBlurb: 'Outsourced bookkeeping, accounting and tax for small businesses across the US, with a dedicated team and fixed-fee pricing.',
    result: 'Fixed-fee accounting', tint: 'linear-gradient(150deg, #1B4332, #06211A)' },
  { name: 'Coastal Tax Advisors', brand: 'COASTAL TAX', domain: 'coastal-tax.com', category: 'Accounting', cat: 'Accounting',
    nav: ['Services', 'Testimonials', 'Consult'], cta: 'Free Consultation', ctaBg: '#4FB3BF', ctaInk: '#04121F',
    heroLine: 'Tax season, simplified.', heroBlurb: 'Personalized tax preparation and planning for individuals, families and short-term rental hosts across the United States.',
    result: 'Clients nationwide', tint: 'linear-gradient(150deg, #0B3D5C, #041D2E)' },
  { name: 'The OG', brand: 'THE OG', domain: 'theogdenver.com', category: 'Restaurants', cat: 'Restaurants',
    nav: ['Menu', 'Locations', 'Order'], cta: 'View Menu', ctaBg: '#E9A94F', ctaInk: '#2A1608',
    heroLine: 'Brunch worth waking up for.', heroBlurb: 'A Denver breakfast and brunch spot built around a menu people crave.',
    result: 'Local favorite', tint: 'linear-gradient(150deg, #7C4A1E, #2A1608)' },
  { name: 'Private Chef Direct', brand: 'PRIVATE CHEF', domain: 'privatechefdirect.com', category: 'Chefs', cat: 'Chefs',
    nav: ['Menus', 'Occasions', 'Enquire'], cta: 'Book A Chef', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'A private chef, at your table.', heroBlurb: 'Bespoke in-home dining with an award-winning private chef, serving the UK and overseas.',
    result: 'Award-winning chef', tint: 'linear-gradient(150deg, #3A2E10, #100C04)' },
  { name: 'Table at Home', brand: 'TABLE AT HOME', domain: 'tableathome.com', category: 'Chefs', cat: 'Chefs',
    nav: ['How It Works', 'Chefs', 'Get Quotes'], cta: 'Get Proposals', ctaBg: '#C6CB8A', ctaInk: '#16210B',
    heroLine: 'A private chef, no guesswork.', heroBlurb: 'Request a private chef online and get competing proposals from vetted personal chefs.',
    result: 'Vetted chef network', tint: 'linear-gradient(150deg, #3E4A1E, #12180A)' },
  { name: 'Yhangry', brand: 'YHANGRY', domain: 'yhangry.com', category: 'Chefs', cat: 'Chefs',
    nav: ['Occasions', 'Chefs', 'Book'], cta: 'Find A Chef', ctaBg: '#E8B4C8', ctaInk: '#2A0F1A',
    heroLine: 'Restaurant-quality, at home.', heroBlurb: 'A marketplace connecting home diners with private chefs for everyday meals and events.',
    result: 'On-demand chefs', tint: 'linear-gradient(150deg, #6E1B4A, #240818)' },
  { name: 'Thomson Legal', brand: 'THOMSON LEGAL', domain: 'thomsonlegal.co.uk', category: 'Legal Services', cat: 'Legal Services',
    nav: ['Services', 'Wills & LPA', 'Contact'], cta: 'Get Advice', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Advice you can rely on.', heroBlurb: 'Property, wills and lasting power of attorney services from a UK legal practice.',
    result: 'Trusted legal advice', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Grow Digital', brand: 'GROW DIGITAL', domain: 'growdigitalservices.com', category: 'Digital Marketing', cat: 'Digital Marketing',
    nav: ['Services', 'Portfolio', 'Contact'], cta: 'Get A Quote', ctaBg: '#4FB3BF', ctaInk: '#04121F',
    heroLine: 'Websites that actually grow your business.', heroBlurb: 'Website design and digital marketing for small businesses across Ireland.',
    result: 'Websites & marketing', tint: 'linear-gradient(150deg, #0B3D5C, #041D2E)' },
  { name: 'FiiZ Drinks', brand: 'FIIZ', domain: 'fiizdrinks.com', category: 'Drinks', cat: 'Drinks',
    nav: ['Menu', 'Locations', 'Rewards'], cta: 'Order Now', ctaBg: '#D6E63A', ctaInk: '#1A2004',
    heroLine: 'Your drink, your way.', heroBlurb: 'A modern soda-fountain concept with thousands of custom drink combinations.',
    result: '10,000+ combinations', tint: 'linear-gradient(150deg, #23291A, #0A0D06)' },
  { name: 'Intelligentsia', brand: 'INTELLIGENTSIA', domain: 'intelligentsia.com', category: 'Coffee', cat: 'Coffee',
    nav: ['Shop', 'Origins', 'Subscribe'], cta: 'Shop Coffee', ctaBg: '#6B4A22', ctaInk: '#FFFFFF',
    heroLine: 'Coffee, sourced with intention.', heroBlurb: 'Direct-trade, freshly roasted coffee, sourced and roasted since 1995.',
    result: 'Direct-trade coffee', tint: 'linear-gradient(150deg, #3E2A12, #140D04)' },
  { name: 'Yacht Share Network', brand: 'YACHT SHARE', domain: 'yachtshare.com', category: 'Yacht Services', cat: 'Yacht Services',
    nav: ['Yachts', 'Ownership', 'Enquire'], cta: 'Explore Yachts', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Yacht ownership, shared sensibly.', heroBlurb: 'A yacht syndication network representing over 1,000 co-owners across 300+ yachts.',
    result: '$1B+ in yachts', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Constructech', brand: 'CONSTRUCTECH', domain: 'constructech.com', category: 'Construction', cat: 'Construction',
    nav: ['News', 'Topics', 'Subscribe'], cta: 'Read More', ctaBg: '#B8621B', ctaInk: '#FFFFFF',
    heroLine: 'Construction technology, covered.', heroBlurb: 'News and insight on the technology shaping the construction industry.',
    result: 'Industry coverage', tint: 'linear-gradient(150deg, #4A2409, #1A0C03)' },
  { name: 'Lux Builders', brand: 'LUX BUILDERS', domain: 'luxbuilders.com', category: 'Builders And Fit-out', cat: 'Builders And Fit-out',
    nav: ['Projects', 'Services', 'Contact'], cta: 'Get A Quote', ctaBg: '#E9A94F', ctaInk: '#2A1608',
    heroLine: 'Custom homes, built right.', heroBlurb: 'A Los Angeles County builder specializing in custom homes and renovations.',
    result: 'Custom home builds', tint: 'linear-gradient(150deg, #4A3B1A, #1A1506)' },
  { name: 'Thomas James Homes', brand: 'TJH', domain: 'tjh.com', category: 'Builders And Fit-out', cat: 'Builders And Fit-out',
    nav: ['Communities', 'Homes', 'Contact'], cta: 'Find A Home', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'A home, guaranteed on time.', heroBlurb: 'New single-lot homes across California, the Pacific Northwest and Arizona, with a guaranteed price and timeline.',
    result: '1,400+ homes delivered', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Shoptiques', brand: 'SHOPTIQUES', domain: 'shoptiques.com', category: 'Boutiques', cat: 'Boutiques',
    nav: ['Shop', 'Boutiques', 'Sale'], cta: 'Shop Now', ctaBg: '#F4F2AE', ctaInk: '#16210B',
    heroLine: 'Independent boutiques, one storefront.', heroBlurb: 'An online marketplace for unique items from thousands of independently owned boutiques.',
    result: '5,000+ boutiques', tint: 'linear-gradient(150deg, #7A2E6B, #2A0F24)' },
  { name: 'Boutique Africaine', brand: 'BOUTIQUE AFRICAINE', domain: 'boutiqueafricaine.com', category: 'Boutiques', cat: 'Boutiques',
    nav: ['Shop', 'Vendors', 'About'], cta: 'Shop Now', ctaBg: '#C6A227', ctaInk: '#1A1004',
    heroLine: 'African style, made accessible.', heroBlurb: 'An online marketplace for African-inspired clothing, jewelry and décor from independent vendors.',
    result: 'Global vendor marketplace', tint: 'linear-gradient(150deg, #8E1B22, #2A0709)' },
  { name: 'Healthcare Pro', brand: 'HEALTHCARE PRO', domain: 'healthcare.pro', category: 'Clinics', cat: 'Clinics',
    nav: ['Find A Doctor', 'Reviews', 'Book'], cta: 'Find A Doctor', ctaBg: '#1B5E6E', ctaInk: '#FFFFFF',
    heroLine: 'Find the right doctor, faster.', heroBlurb: 'A platform connecting patients with physicians through reviews and easy appointment booking.',
    result: 'Verified physician reviews', tint: 'linear-gradient(150deg, #1B5E6E, #062730)' },
  { name: 'Matbakh Vibes', brand: 'MATBAKH VIBES', domain: 'matbakhvibes.com', category: 'E-commerce', cat: 'E-commerce',
    nav: ['Shop', 'Organizers', 'About'], cta: 'Shop Now', ctaBg: '#F4F2AE', ctaInk: '#16210B',
    heroLine: 'A kitchen that works, and looks it.', heroBlurb: 'Smart kitchen organizers and luxury serveware, delivered free across the UAE.',
    result: 'Free UAE delivery', tint: 'linear-gradient(150deg, #7A2E6B, #2A0F24)' },
  { name: 'Atlas IoT', brand: 'ATLAS IOT', domain: 'atlasiot.com', category: 'Agriculture', cat: 'Agriculture',
    nav: ['Solutions', 'Technology', 'Contact'], cta: 'Get In Touch', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Smarter data from the field.', heroBlurb: 'IoT connectivity and sensor solutions built for agriculture and industry.',
    result: 'IoT for agriculture', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Agribusiness.pro', brand: 'AGRIBUSINESS', domain: 'agribusiness.pro', category: 'Agriculture', cat: 'Agriculture',
    nav: ['Solutions', 'About', 'Contact'], cta: 'Learn More', ctaBg: '#6B4A22', ctaInk: '#FFFFFF',
    heroLine: 'Digital transformation for agribusiness.', heroBlurb: 'Innovation and digital transformation consulting for the agribusiness sector.',
    result: 'Agribusiness innovation', tint: 'linear-gradient(150deg, #3E2A12, #140D04)' },
  { name: 'Phone Store', brand: 'PHONE STORE', domain: 'phonestore.com.au', category: 'Telecommunications', cat: 'Telecommunications',
    nav: ['Plans', 'Devices', 'Contact'], cta: 'View Plans', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Mobile plans, made simple.', heroBlurb: 'A mobile phone and telecom retailer serving customers across Australia.',
    result: 'Mobile plans & devices', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'FIVI Communication', brand: 'FIVI', domain: 'fivicomm.com', category: 'Telecommunications', cat: 'Telecommunications',
    nav: ['Internet', 'IPTV', 'CCTV'], cta: 'Get Connected', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Connectivity, done reliably.', heroBlurb: 'Internet, IPTV and CCTV services for homes and businesses in Chakwal and Talagang.',
    result: 'Reliable local connectivity', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Entertainment.com.au', brand: 'ENTERTAINMENT', domain: 'entertainment.com.au', category: 'Media & Entertainment', cat: 'Media & Entertainment',
    nav: ['Offers', 'App', 'Sign Up'], cta: 'Get The App', ctaBg: '#E8B4C8', ctaInk: '#2A0F1A',
    heroLine: 'Discounts on what you love doing.', heroBlurb: 'An app offering exclusive discounts and things to do across Australia and New Zealand.',
    result: 'Thousands of discounts', tint: 'linear-gradient(150deg, #6E1B4A, #240818)' },
  { name: 'Production Services', brand: 'PRODUCTION SERVICES', domain: 'productionservices.net', category: 'Metal & Engineering', cat: 'Metal & Engineering',
    nav: ['Machining', 'Supply', 'Contact'], cta: 'Get A Quote', ctaBg: '#B8621B', ctaInk: '#FFFFFF',
    heroLine: 'Precision machining, done in-house.', heroBlurb: 'A full-service machine shop and industrial supply store offering machining and welding in Del Rey, CA.',
    result: 'Full-service machine shop', tint: 'linear-gradient(150deg, #4A2409, #1A0C03)' },
  { name: 'Facility Management Pros', brand: 'FACILITY MGMT PROS', domain: 'facilitymanagement.pro', category: 'Security & Facility Management', cat: 'Security & Facility Management',
    nav: ['Services', 'Areas', 'Get A Quote'], cta: 'Free Quote', ctaBg: '#1B5E6E', ctaInk: '#FFFFFF',
    heroLine: 'Cleaning you can verify.', heroBlurb: 'Commercial cleaning across New Hampshire and Massachusetts, with photo-verified quality and no long-term contracts.',
    result: 'Photo-verified cleaning', tint: 'linear-gradient(150deg, #1B5E6E, #062730)' },
  { name: 'CCI Training Center', brand: 'CCI TRAINING', domain: 'ccitraining.edu', category: 'Education & Training', cat: 'Education & Training',
    nav: ['Programs', 'Certifications', 'Enroll'], cta: 'Enroll Now', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'A career, one certification away.', heroBlurb: 'Accredited online career training and fast-track certifications, building careers since 1984.',
    result: '24,000+ graduates', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Aircraft Hire', brand: 'AIRCRAFT HIRE', domain: 'aircrafthire.au', category: 'Aviation', cat: 'Aviation',
    nav: ['Aircraft', 'Rates', 'Book'], cta: 'Book Now', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Take the controls.', heroBlurb: 'Private aircraft hire for licensed pilots at Archerfield Airport in Brisbane.',
    result: 'Licensed pilot hire', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Mohawk Global', brand: 'MOHAWK GLOBAL', domain: 'mohawkglobal.com', category: 'Import & Export', cat: 'Import & Export',
    nav: ['Services', 'Compliance', 'Contact'], cta: 'Get In Touch', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Global trade, simplified.', heroBlurb: 'International logistics, trade compliance and supply chain solutions.',
    result: 'Global logistics network', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Lions Sale Group', brand: 'LIONS SALE GROUP', domain: 'lionssg.com', category: 'Import & Export', cat: 'Import & Export',
    nav: ['Products', 'Sourcing', 'Contact'], cta: 'Get A Quote', ctaBg: '#B8621B', ctaInk: '#FFFFFF',
    heroLine: 'Sourced right, delivered globally.', heroBlurb: 'Import/export, sourcing and bleach manufacturing services trusted globally since 2020.',
    result: 'Global sourcing since 2020', tint: 'linear-gradient(150deg, #4A2409, #1A0C03)' },
  { name: 'GEM Enterprise', brand: 'GEM ENTERPRISE', domain: 'gementerprise.uk', category: 'Metal & Engineering', cat: 'Metal & Engineering',
    nav: ['Services', 'Projects', 'Contact'], cta: 'Get In Touch', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Engineering, built to hold.', heroBlurb: 'A UK structural, civil and architectural engineering consultancy.',
    result: 'Structural engineering', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Metalworks', brand: 'METALWORKS', domain: 'metalworks.com.au', category: 'Metal & Engineering', cat: 'Metal & Engineering',
    nav: ['Services', 'Capabilities', 'Quote'], cta: 'Get A Quote', ctaBg: '#B8621B', ctaInk: '#FFFFFF',
    heroLine: 'Precision cutting, delivered fast.', heroBlurb: 'A Melbourne-based metal laser cutting service for businesses across the region.',
    result: 'Precision laser cutting', tint: 'linear-gradient(150deg, #4A2409, #1A0C03)' },
  { name: 'Solar Services', brand: 'SOLAR SERVICES', domain: 'solarservices.com.au', category: 'Energy & Renewables', cat: 'Energy & Renewables',
    nav: ['Services', 'Solar', 'Contact'], cta: 'Get A Quote', ctaBg: '#D6E63A', ctaInk: '#1A2004',
    heroLine: 'Solar, installed and maintained.', heroBlurb: 'Solar system installation, service and maintenance on the Central Coast.',
    result: 'Local solar experts', tint: 'linear-gradient(150deg, #23291A, #0A0D06)' },
  { name: 'CarParts.com.au', brand: 'CARPARTS', domain: 'carparts.com.au', category: 'Automotive Parts', cat: 'Automotive Parts',
    nav: ['Shop', 'Brands', 'Support'], cta: 'Shop Parts', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'The right part, verified to fit.', heroBlurb: 'Genuine and OE-matching parts for European vehicles, fitment-verified and fast to ship.',
    result: 'Fitment-verified parts', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'PrintingForLess', brand: 'PRINTINGFORLESS', domain: 'printingforless.com', category: 'Printing & Packaging', cat: 'Printing & Packaging',
    nav: ['Products', 'Design', 'Get A Quote'], cta: 'Get A Quote', ctaBg: '#B8621B', ctaInk: '#FFFFFF',
    heroLine: 'Print, mailed and delivered.', heroBlurb: 'Online printing and direct mail services built for growing businesses.',
    result: 'Business printing & mail', tint: 'linear-gradient(150deg, #4A2409, #1A0C03)' },
  { name: 'Luzaro Fragrances', brand: 'LUZARO', domain: 'luzarofragrances.com', category: 'Perfume & Fragrance', cat: 'Perfume & Fragrance',
    nav: ['Shop', 'Collections', 'About'], cta: 'Shop Now', ctaBg: '#7A2E6B', ctaInk: '#FFFFFF',
    heroLine: 'Fragrance, delivered fresh.', heroBlurb: 'Pakistan\'s premier online fragrance shop, with free delivery above 5,000 PKR.',
    result: 'Free delivery in Pakistan', tint: 'linear-gradient(150deg, #7A2E6B, #2A0F24)' },
  { name: 'Unique\'e Luxury', brand: 'UNIQUE\'E LUXURY', domain: 'uniqueeluxury.com', category: 'Perfume & Fragrance', cat: 'Perfume & Fragrance',
    nav: ['Shop', 'Collection', 'About'], cta: 'Shop Now', ctaBg: '#6E1B4A', ctaInk: '#FFFFFF',
    heroLine: 'A scent that stays with you.', heroBlurb: 'Refined unisex Extrait de Parfum fragrances crafted for lasting presence.',
    result: 'Unisex luxury fragrances', tint: 'linear-gradient(150deg, #6E1B4A, #240818)' },
  { name: 'UnPop!', brand: 'UNPOP', domain: 'drinkunpop.com', category: 'Drinks', cat: 'Drinks',
    nav: ['Shop', 'Flavors', 'Story'], cta: 'Shop Now', ctaBg: '#D6E63A', ctaInk: '#1A2004',
    heroLine: 'Soda, radically honest.', heroBlurb: 'Botanical craft sodas made with real, honestly-labeled ingredients.',
    result: 'Craft botanical sodas', tint: 'linear-gradient(150deg, #23291A, #0A0D06)' },
  { name: 'White & Co', brand: 'WHITE & CO', domain: 'whiteandcogroup.com', category: 'Real Estate', cat: 'Real Estate',
    nav: ['Properties', 'Buy', 'Sell'], cta: 'View Properties', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Dubai real estate, done right.', heroBlurb: 'A Dubai real estate brokerage helping buyers, sellers and investors navigate the market.',
    result: 'Dubai property experts', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Driven Properties', brand: 'DRIVEN PROPERTIES', domain: 'drivenproperties.com', category: 'Real Estate', cat: 'Real Estate',
    nav: ['Properties', 'Developers', 'Contact'], cta: 'View Listings', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Property, driven by results.', heroBlurb: 'A Dubai real estate agency connecting buyers and investors with residential and commercial properties.',
    result: 'Residential & commercial', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Oakdale Auto Dubai', brand: 'OAKDALE AUTO', domain: 'oakdaleautodubai.com', category: 'Automotive', cat: 'Automotive',
    nav: ['Inventory', 'Sell Your Car', 'Contact'], cta: 'View Inventory', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Your next car, in Dubai.', heroBlurb: 'A Dubai-based used car dealership helping buyers find and finance their next vehicle.',
    result: 'Dubai car dealership', tint: 'linear-gradient(150deg, #1A1A1A, #050505)' },
  { name: 'Firelands Wealth Management', brand: 'FIRELANDS', domain: 'firelandswealth.com', category: 'Banking & Finance', cat: 'Banking & Finance',
    nav: ['Services', 'Planning', 'Contact'], cta: 'Get Started', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Your personal CFO.', heroBlurb: 'Financial advisory and estate planning built around a single point of accountability.',
    result: 'Personal CFO service', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'JMS Financial Solutions', brand: 'JMS FINANCIAL', domain: 'jmsfinancialsolutions.com', category: 'Banking & Finance', cat: 'Banking & Finance',
    nav: ['Services', 'About', 'Contact'], cta: 'Get In Touch', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Financial solutions, made personal.', heroBlurb: 'Financial planning and advisory solutions for individuals and businesses.',
    result: 'Personalized financial planning', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Colorland Toys', brand: 'COLORLAND', domain: 'colorlandtoys.com', category: 'Kids & Toys', cat: 'Kids & Toys',
    nav: ['Shop', 'Brands', 'Delivery'], cta: 'Shop Now', ctaBg: '#D6E63A', ctaInk: '#1A2004',
    heroLine: 'Play, delivered fast.', heroBlurb: 'The UAE\'s largest toy retailer, with quality toys, games and playsets delivered fast.',
    result: 'Leading UAE toy retailer', tint: 'linear-gradient(150deg, #23291A, #0A0D06)' },
  { name: 'Click Pharmacy', brand: 'CLICK PHARMACY', domain: 'clickpharmacy.co.uk', category: 'Pharmaceutical & Healthcare Products', cat: 'Pharmaceutical & Healthcare Products',
    nav: ['Prescriptions', 'Shop', 'NHS'], cta: 'Order Now', ctaBg: '#1B5E6E', ctaInk: '#FFFFFF',
    heroLine: 'Your pharmacy, online.', heroBlurb: 'A UK online pharmacy offering NHS and private prescriptions with secure, convenient delivery.',
    result: 'NHS & private prescriptions', tint: 'linear-gradient(150deg, #1B5E6E, #062730)' },
  { name: 'Sehaaonline', brand: 'SEHAAONLINE', domain: 'sehaaonline.com', category: 'Pharmaceutical & Healthcare Products', cat: 'Pharmaceutical & Healthcare Products',
    nav: ['Shop', 'Categories', 'Contact'], cta: 'Shop Now', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Medical supplies, sourced right.', heroBlurb: 'A leading Dubai supplier of hospital medical equipment and healthcare products.',
    result: 'Leading medical supplier', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
  { name: 'Ash Pet Shop', brand: 'ASH PET SHOP', domain: 'ashpetshop.ae', category: 'Pet Industry', cat: 'Pet Industry',
    nav: ['Shop', 'Cats', 'Contact'], cta: 'Shop Now', ctaBg: '#E8B4C8', ctaInk: '#2A0F1A',
    heroLine: 'Everything for your cat.', heroBlurb: 'A pet shop specializing in products for cats, from food to toys and accessories.',
    result: 'Cat specialists', tint: 'linear-gradient(150deg, #6E1B4A, #240818)' },
  { name: 'Elite Vet Clinic', brand: 'ELITE VET CLINIC', domain: 'elitevetclinic.ae', category: 'Pet Industry', cat: 'Pet Industry',
    nav: ['Services', 'Book', 'Contact'], cta: 'Book Now', ctaBg: '#8A6D1E', ctaInk: '#FFFFFF',
    heroLine: 'Care your pet can count on.', heroBlurb: 'A Sharjah veterinary clinic offering checkups, vaccinations, surgery and grooming for dogs and cats.',
    result: 'Full-service vet care', tint: 'linear-gradient(150deg, #2B2410, #0F0C04)' },
  { name: 'Saifco Travel & Tourism', brand: 'SAIFCO', domain: 'mysaifco.com', category: 'Travel', cat: 'Travel',
    nav: ['Services', 'Umrah', 'Contact'], cta: 'Get A Quote', ctaBg: '#0A3D62', ctaInk: '#FFFFFF',
    heroLine: 'Travel, arranged properly.', heroBlurb: 'A UAE travel agency offering Umrah packages, visas and international tours.',
    result: 'Umrah, visas & tours', tint: 'linear-gradient(150deg, #0A3D62, #041B2E)' },
]

export const EXAMPLE_CATEGORIES = [
  'All', 'Accounting', 'Restaurants', 'Chefs', 'Flower Store', 'Legal Services', 'Digital Marketing', 'Real Estate', 'Wedding And Caterers', 'Drinks', 'Coffee', 'Travel', 'Yacht Services', 'Construction', 'Builders And Fit-out', 'Boutiques', 'Clinics', 'Salons', 'Textiles', 'E-commerce', 'Trades', 'Gyms And Fitness', 'Jewelry & Luxury Goods', 'Automotive', 'Banking & Finance', 'Agriculture', 'Telecommunications', 'Pet Industry', 'Media & Entertainment', 'Security & Facility Management', 'Education & Training', 'Kids & Toys', 'Aviation', 'Import & Export', 'Metal & Engineering', 'Energy & Renewables', 'Automotive Parts', 'Home Services', 'Pharmaceutical & Healthcare Products', 'Printing & Packaging', 'Perfume & Fragrance',
]

// Cross-reference from each rail category above to the matching
// industry (or industries) in the platform's own onboarding taxonomy
// (matjarx-platform/src/lib/industries.ts), plus a plain-English
// description of the businesses each category covers — kept here so
// the two taxonomies can be reconciled deliberately if either changes,
// rather than drifting apart silently. Not wired into the rail UI.
export const EXAMPLE_CATEGORY_INDUSTRIES: Record<string, string> = {
  'All': 'All Categories',
  'Accounting': 'Professional Business Services',
  'Restaurants': 'Food & Beverage, Tourism & Hospitality',
  'Chefs': 'Food & Beverage, Personal Services',
  'Flower Store': 'E-Commerce & Retail',
  'Legal Services': 'Legal Services',
  'Digital Marketing': 'Digital Marketing & Creative Services',
  'Real Estate': 'Construction & Real Estate',
  'Wedding And Caterers': 'Events & Weddings, Food & Beverage',
  'Drinks': 'Food & Beverage',
  'Coffee': 'Food & Beverage',
  'Travel': 'Tourism & Hospitality',
  'Yacht Services': 'Marine & Fisheries, Tourism & Hospitality',
  'Construction': 'Construction & Real Estate',
  'Builders And Fit-out': 'Construction & Real Estate',
  'Boutiques': 'E-Commerce & Retail',
  'Clinics': 'Healthcare & Medical',
  'Salons': 'Beauty & Personal Care, Personal Services',
  'Textiles': 'Textile & Apparel',
  'E-commerce': 'E-Commerce & Retail',
  'Trades': 'Professional Business Services, Home Services',
  'Gyms And Fitness': 'Sports & Fitness',
  'Jewelry & Luxury Goods': 'Jewelry boutiques, luxury watch retailers, designer accessory stores',
  'Automotive': 'Car dealerships, auto repair shops, car rental services, mechanics',
  'Banking & Finance': 'Banks, financial advisors, insurance brokers, fintech platforms',
  'Agriculture': 'Farms, agricultural equipment suppliers, food processors, nurseries',
  'Telecommunications': 'Mobile phone shops, internet service providers, telecom retailers',
  'Pet Industry': 'Pet stores, veterinary clinics, pet grooming, pet training centers, pet supplies',
  'Media & Entertainment': 'Publishing houses, production companies, entertainment venues, cinema',
  'Security & Facility Management': 'Security services, cleaning services, facility management companies',
  'Education & Training': 'Training centers, coaching institutes, online education platforms, universities',
  'Kids & Toys': 'Toy stores, kids clothing boutiques, play centers, daycare services',
  'Aviation': 'Airlines, flight training centers, aviation maintenance, aircraft services',
  'Import & Export': 'Trading companies, freight forwarders, customs brokers, import/export agents',
  'Metal & Engineering': 'Engineering firms, metal fabrication, welding shops, machinery suppliers',
  'Energy & Renewables': 'Solar installation, renewable energy providers, energy consulting, electrical contractors',
  'Automotive Parts': 'Auto parts stores, accessory shops, spare parts dealers',
  'Home Services': 'Plumbing services, electrical services, HVAC, painting, carpentry',
  'Pharmaceutical & Healthcare Products': 'Pharmacies, medical equipment suppliers, health product retailers',
  'Printing & Packaging': 'Printing services, packaging design, label manufacturers, graphic design studios',
  'Perfume & Fragrance': 'Beauty & Personal Care',
}

export const EXAMPLE_PILLARS = [
  { title: 'Category expertise', body: 'Your site is built by a designer who has worked in your trade before — so the layout, the words and the features actually fit how you sell.', icon: 'M12 3.5 4.5 7.5v9L12 20.5l7.5-4v-9ZM12 12l7.5-4.5M12 12v8.5M12 12 4.5 7.5' },
  { title: 'Personalisation', body: "We showcase your brand and your unique selling points. Your website tells your story — not a template's.", icon: 'M12 12a3.6 3.6 0 1 0 0-7.2 3.6 3.6 0 0 0 0 7.2ZM4.5 20a7.5 7.5 0 0 1 15 0' },
  { title: 'Easy to run', body: 'Simple to launch, use and update. And help from a real person is always a message or a phone call away.', icon: 'M12 15.1a3.1 3.1 0 1 0 0-6.2 3.1 3.1 0 0 0 0 6.2ZM4.6 12a7.4 7.4 0 0 1 .1-1.2l-2-1.5 2-3.4 2.3 1a7.6 7.6 0 0 1 2-1.2l.3-2.5h4l.3 2.5a7.6 7.6 0 0 1 2 1.2l2.3-1 2 3.4-2 1.5a7.4 7.4 0 0 1 0 2.4l2 1.5-2 3.4-2.3-1a7.6 7.6 0 0 1-2 1.2l-.3 2.5h-4l-.3-2.5a7.6 7.6 0 0 1-2-1.2l-2.3 1-2-3.4 2-1.5A7.4 7.4 0 0 1 4.6 12Z' },
]
