// Data for the 7 Help article pages — from files/matjarx_help_*.md.
// Each category is one long-form guide (not a list of separate articles);
// generated from the source markdown's own section/list/FAQ structure.

export type HelpSlug =
  | "getting-started"
  | "website-editor"
  | "domains-and-email"
  | "billing-and-plans"
  | "ecommerce-and-payments"
  | "seo-and-marketing"
  | "account-and-security"

export const HELP_SLUGS: HelpSlug[] = ["getting-started", "website-editor", "domains-and-email", "billing-and-plans", "ecommerce-and-payments", "seo-and-marketing", "account-and-security"]

export type HelpBlock =
  | { type: 'h3'; text: string }
  | { type: 'h4'; text: string }
  | { type: 'p'; text: string }
  | { type: 'ul'; items: string[] }

export type HelpArticle = {
  title: string
  metaTitle: string
  metaDesc: string
  intro?: string
  metaLines?: string[]
  heroImage?: { src: string; alt: string; width: number; height: number }
  sections: { heading: string; blocks: HelpBlock[] }[]
  faqs: [string, string][]
  related: [string, string][]
}

export const HELP_ARTICLES: Record<HelpSlug, HelpArticle> = {
  "getting-started": {
    title: "Getting Started With MatjarX",
    metaTitle: "Getting Started - Website Onboarding & Launch Process",
    metaDesc: "Welcome to MatjarX! Follow our step-by-step onboarding guide to get your website launched in 7 days. Includes questionnaire and launch call.",
    intro: "Getting started is simple. We'll guide you through every step from signup to launch.",
    metaLines: ["Timeline: 7-45 days depending on your plan", "Total time commitment: 2-3 hours over the onboarding period"],
    heroImage: { src: '/services/questionnaire-brief.webp', alt: 'A finished MatjarX-built website shown in the editor', width: 453, height: 373 },
    sections: [
      { heading: "Step 1: Sign Up (10 minutes)", blocks: [
        { type: "h3", text: "Create Your MatjarX Account" },
        { type: 'p', text: "**Visit matjarx.com and click \"Get Started\"**" },
        { type: 'p', text: "**Enter:**" },
        { type: 'ul', items: ["Email address", "Password", "Business name", "Business type"] },
        { type: 'p', text: "**Choose your plan** (Launch, Boost, Growth, Platinum, or Custom)" },
        { type: 'p', text: "**Complete payment** for setup fee + first month" },
        { type: 'p', text: "**Check your email** for welcome message and next steps" },
      ] },
      { heading: "Step 2: Complete Website Questionnaire (45 minutes)", blocks: [
        { type: "h3", text: "Tell Us About Your Business" },
        { type: 'p', text: "You'll receive an email with a questionnaire link. This helps us build your website correctly." },
        { type: 'p', text: "**Sections to complete:**" },
        { type: 'p', text: "**Business Information**" },
        { type: 'ul', items: ["Business name and tagline", "What you do (description)", "Years in business", "Target customer", "Geographic service area"] },
        { type: 'p', text: "**Website Goals**" },
        { type: 'ul', items: ["Main goal (leads, sales, information)", "What visitors should do on your site", "Your success metrics"] },
        { type: 'p', text: "**Content & Design**" },
        { type: 'ul', items: ["Brand colors or preferences", "Logo (if you have one)", "Photos to include", "Websites you like", "Competitor sites (for reference)"] },
        { type: 'p', text: "**Technical Needs**" },
        { type: 'ul', items: ["Custom domain? (We can register one)", "Email accounts needed?", "Special features?", "Payment processing?"] },
        { type: "h3", text: "Tips for Better Results" },
        { type: 'ul', items: ["✅ Be specific and detailed", "✅ Gather photos, logos, and content", "✅ Have competitor URLs ready", "✅ Answer all questions", "✅ Don't rush—takes 30-45 minutes"] },
      ] },
      { heading: "Step 3: Schedule Launch Call (5 minutes)", blocks: [
        { type: "h3", text: "Meet Your MatjarX Team" },
        { type: 'p', text: "**A 30-45 minute video call to discuss your website**" },
        { type: 'p', text: "**What to expect:**" },
        { type: 'ul', items: ["Introduction to your account manager", "Questions about your vision", "Clarifying timeline and next steps", "Discussing design and features", "Answering your questions"] },
        { type: 'p', text: "**How to schedule:**" },
        { type: 'ul', items: ["Check your welcome email", "Click calendar link", "Choose time (Mon-Sat, 11 AM - 8 PM PKT)", "Confirm"] },
        { type: 'p', text: "**Have ready:**" },
        { type: 'ul', items: ["Your completed questionnaire", "Photos or logo", "List of key pages", "Any special requirements"] },
      ] },
      { heading: "Step 4: Build Phase (7-45 days)", blocks: [
        { type: "h3", text: "What Happens During Build" },
        { type: 'p', text: "**Week 1:**" },
        { type: 'ul', items: ["Website structure designed", "Pages laid out", "Content entered", "Design theme applied"] },
        { type: 'p', text: "**Week 2-3 (depending on plan):**" },
        { type: 'ul', items: ["Pages refined", "Features configured", "Email accounts created (if applicable)", "Integrations setup"] },
        { type: 'p', text: "**Week 4+ (Platinum & Custom):**" },
        { type: 'ul', items: ["Advanced features", "Complex integrations", "Optimization", "Testing"] },
        { type: "h3", text: "What You Do" },
        { type: 'p', text: "**Provide Content & Materials:**" },
        { type: 'ul', items: ["Write business description", "Send photos and logos", "Confirm service/product info", "Provide team bios"] },
        { type: 'p', text: "**Review & Approve:**" },
        { type: 'ul', items: ["Check design mockups", "Review content", "Provide feedback", "Approve before launch"] },
        { type: "h3", text: "Communication" },
        { type: 'p', text: "**You'll receive:**" },
        { type: 'ul', items: ["Email updates every 3-5 days", "Preview links for review", "Questions via WhatsApp or email", "Response within 24-48 hours"] },
      ] },
      { heading: "Step 5: Pre-Launch Review (2-3 days)", blocks: [
        { type: "h3", text: "Final Check Before Going Live" },
        { type: 'p', text: "**You'll receive:** A preview link to review everything" },
        { type: 'p', text: "**Check:**" },
        { type: 'ul', items: ["✅ All pages display correctly", "✅ Mobile design looks good", "✅ Forms work properly", "✅ Email functions (if applicable)", "✅ Payment works (if applicable)", "✅ All images load", "✅ Links work"] },
        { type: 'p', text: "**Report any issues** and we'll fix them immediately" },
      ] },
      { heading: "Step 6: Launch! (1 day)", blocks: [
        { type: "h3", text: "Your Website Goes Live" },
        { type: 'p', text: "**What happens:**" },
        { type: 'ul', items: ["Domain activates", "Website deployed to live servers", "Analytics activated", "Google Search Console setup", "Confirmation email sent"] },
        { type: 'p', text: "**Your website is now live and visible to the world!**" },
      ] },
      { heading: "Need Help?", blocks: [
        { type: 'p', text: "**Contact us anytime:**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["How long until my website is live?", "Typically 7-45 days depending on your plan. Launch Plan takes 7 days, Platinum takes 30-45 days."],
      ["What if I don't have content ready?", "We can write it for you (additional cost) or we can launch with placeholder content you fill in later."],
      ["Can I edit my website after launch?", "Yes! You can edit anytime using our editor, or request our help."],
      ["What if I'm not happy with the design?", "We include feedback rounds during the build. You approve before launch, so you control the final result."],
      ["Do I need to know how to use the website?", "No! We can make changes for you, or we can train you to edit it yourself."]
    ],
    related: [["Website Editor", "/help/website-editor/"], ["Domain & Email Setup", "/help/domains-and-email/"], ["SEO & Marketing", "/help/seo-and-marketing/"], ["Billing & Plans", "/help/billing-and-plans/"]],
  },
  "website-editor": {
    title: "Website Editor Guide",
    metaTitle: "Website Editor - Edit & Customize Your Website",
    metaDesc: "Learn to edit your MatjarX website. Step-by-step guide to making changes, adding content, and self-serve website customization.",
    heroImage: { src: '/services/design-build.webp', alt: 'A website design editor with font and color controls', width: 1190, height: 980 },
    sections: [
      { heading: "Getting Started With the Editor", blocks: [
        { type: "h3", text: "Accessing Your Website Editor" },
        { type: 'p', text: "**Login to your dashboard:**" },
        { type: 'ul', items: ["Go to matjarx.com", "Click \"Login\"", "Enter your email and password", "Click \"Edit Website\""] },
        { type: 'p', text: "**The editor opens in a new window**" },
      ] },
      { heading: "Website Editor Basics", blocks: [
        { type: "h3", text: "Interface Overview" },
        { type: 'p', text: "**Left Sidebar:**" },
        { type: 'ul', items: ["Pages list", "Add new page", "Settings", "Help"] },
        { type: 'p', text: "**Main Canvas:**" },
        { type: 'ul', items: ["Your website preview", "Drag-and-drop elements", "Text and image editing"] },
        { type: 'p', text: "**Right Panel:**" },
        { type: 'ul', items: ["Element settings", "Design options", "Advanced settings"] },
        { type: "h3", text: "Saving Your Changes" },
        { type: 'p', text: "**Save automatically** - Changes save as you work (most things)" },
        { type: 'p', text: "**For major changes:**" },
        { type: 'ul', items: ["Click \"Save\" button", "Wait for confirmation", "Check preview"] },
        { type: 'p', text: "**Never lose work** - Auto-save activates every 30 seconds" },
      ] },
      { heading: "Editing Content", blocks: [
        { type: "h3", text: "Changing Text" },
        { type: 'p', text: "**To edit text on your site:**" },
        { type: 'ul', items: ["Click the text element", "Type your new content", "Format as needed (bold, italic, etc.)", "Click outside to finish", "Changes save automatically"] },
        { type: "h3", text: "Editing Images" },
        { type: 'p', text: "**To replace an image:**" },
        { type: 'ul', items: ["Click the image", "Click \"Change Image\"", "Upload from your computer", "Click \"Select\"", "Image updates immediately"] },
        { type: 'p', text: "**To resize an image:**" },
        { type: 'ul', items: ["Click the image", "Drag corner handles to resize", "Keep aspect ratio to avoid distortion"] },
        { type: "h3", text: "Adding New Content" },
        { type: 'p', text: "**To add text:**" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Text\"", "Type your content", "Style as needed"] },
        { type: 'p', text: "**To add images:**" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Image\"", "Upload from computer", "Position and resize"] },
        { type: 'p', text: "**To add buttons:**" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Button\"", "Enter button text", "Set button link/action"] },
      ] },
      { heading: "Working With Pages", blocks: [
        { type: "h3", text: "Adding a New Page" },
        { type: 'p', text: "**To create a new page:**" },
        { type: 'ul', items: ["Click \"+\" next to Pages list", "Enter page name", "Choose template or start blank", "Page is created", "Edit content as needed"] },
        { type: 'p', text: "**Good page names:**" },
        { type: 'ul', items: ["Services", "About Us", "Contact", "Blog", "FAQ", "Testimonials"] },
        { type: "h3", text: "Editing Page Settings" },
        { type: 'p', text: "**To edit page details:**" },
        { type: 'ul', items: ["Right-click page name", "Click \"Settings\"", "Edit page title", "Edit page URL (slug)", "Set SEO details", "Save"] },
        { type: "h3", text: "Organizing Pages" },
        { type: 'p', text: "**To reorder pages:**" },
        { type: 'ul', items: ["Drag page name in sidebar", "Drop in new position", "Order updates immediately"] },
        { type: 'p', text: "**This affects navigation order**" },
        { type: "h3", text: "Hiding/Deleting Pages" },
        { type: 'p', text: "**To hide a page:**" },
        { type: 'ul', items: ["Right-click page", "Click \"Hide from Navigation\"", "Page is hidden from menu (but still accessible)"] },
        { type: 'p', text: "**To delete a page:**" },
        { type: 'ul', items: ["Right-click page", "Click \"Delete\"", "Confirm deletion", "Page is permanently removed"] },
        { type: 'p', text: "**Caution:** Deleting is permanent. Pages are not recoverable." },
      ] },
      { heading: "Design & Customization", blocks: [
        { type: "h3", text: "Changing Colors" },
        { type: 'p', text: "**To change site colors:**" },
        { type: 'ul', items: ["Go to \"Settings\" → \"Design\"", "Click \"Colors\"", "Choose primary color", "Choose accent color", "All pages update automatically"] },
        { type: "h3", text: "Changing Fonts" },
        { type: 'p', text: "**To change typography:**" },
        { type: 'ul', items: ["Go to \"Settings\" → \"Design\"", "Click \"Fonts\"", "Choose header font", "Choose body font", "Preview updates"] },
        { type: "h3", text: "Using Themes" },
        { type: 'p', text: "**To change theme:**" },
        { type: 'ul', items: ["Go to \"Settings\" → \"Theme\"", "Browse available themes", "Click \"Preview\"", "Click \"Apply\" to use", "Your site updates immediately"] },
        { type: 'p', text: "**All your content transfers** to the new theme" },
        { type: "h3", text: "Custom Design" },
        { type: 'p', text: "**For advanced customization:**" },
        { type: 'ul', items: ["Boost Plan: Limited custom options", "Growth Plan: More customization", "Platinum/Custom: Full customization"] },
        { type: 'p', text: "Contact support for advanced design changes." },
      ] },
      { heading: "SEO & Content Optimization", blocks: [
        { type: "h3", text: "Setting Page SEO" },
        { type: 'p', text: "**To optimize for search engines:**" },
        { type: 'ul', items: ["Edit a page", "Click \"SEO Settings\"", "Enter meta title (60 chars)", "Enter meta description (155 chars)", "Add keywords (optional)", "Save"] },
        { type: "h3", text: "Optimizing Content" },
        { type: 'p', text: "**Best practices:**" },
        { type: 'ul', items: ["Use keywords naturally in content", "Write clear, descriptive headings", "Include images with alt text", "Link to related pages", "Write substantial content (300+ words)"] },
        { type: "h3", text: "Adding Meta Information" },
        { type: 'p', text: "**Meta Title:** What appears in Google search results **Meta Description:** Preview text under title in results **Keywords:** (Optional) Helps with search optimization" },
      ] },
      { heading: "Publishing Your Website", blocks: [
        { type: "h3", text: "Going Live" },
        { type: 'p', text: "**Before publishing:**" },
        { type: 'ul', items: ["Review all pages", "Check links work", "Verify images display", "Test mobile view", "Proofread content"] },
        { type: 'p', text: "**To publish:**" },
        { type: 'ul', items: ["Click \"Publish\"", "Review changes", "Confirm publication", "Website updates immediately"] },
        { type: 'p', text: "**Changes go live instantly**" },
        { type: "h3", text: "Scheduling Posts" },
        { type: 'p', text: "**To schedule content:**" },
        { type: 'ul', items: ["Create your content", "Click \"Schedule\"", "Choose date and time", "Content publishes automatically"] },
        { type: 'p', text: "Great for:" },
        { type: 'ul', items: ["Blog posts", "Promotions", "Announcements", "Seasonal content"] },
      ] },
      { heading: "Advanced Features", blocks: [
        { type: "h3", text: "Contact Forms" },
        { type: 'p', text: "**To add a contact form:**" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Contact Form\"", "Customize fields", "Set email destination", "Submissions sent to your email"] },
        { type: "h3", text: "Embedding Content" },
        { type: 'p', text: "**To embed videos, maps, etc:**" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Embed\"", "Paste embed code", "Customize size", "Save"] },
        { type: 'p', text: "Supports YouTube, Maps, social posts, etc." },
        { type: "h3", text: "E-Commerce Features (Platinum Only)" },
        { type: 'p', text: "**Product management:**" },
        { type: 'ul', items: ["Click \"Add Product\"", "Enter product details", "Set price", "Add images", "Configure variants", "Save"] },
        { type: 'p', text: "**Order management:**" },
        { type: 'ul', items: ["Track incoming orders", "Update order status", "Send order notifications", "Generate invoices"] },
      ] },
      { heading: "Mobile Preview", blocks: [
        { type: "h3", text: "Testing Mobile View" },
        { type: 'p', text: "**To see mobile version:**" },
        { type: 'ul', items: ["Click \"Mobile\" button (right side)", "Preview shows mobile display", "Adjust design for mobile if needed", "Toggle back to desktop"] },
        { type: 'p', text: "**Important:** Test all pages on mobile" },
        { type: "h3", text: "Mobile Optimization" },
        { type: 'p', text: "**Ensure:**" },
        { type: 'ul', items: ["✅ Text is readable", "✅ Buttons are large enough to tap", "✅ Images display properly", "✅ No horizontal scrolling", "✅ Forms are easy to use"] },
      ] },
      { heading: "Troubleshooting", blocks: [
        { type: "h3", text: "Changes Not Saving" },
        { type: 'p', text: "**If changes don't save:**" },
        { type: 'ul', items: ["Check internet connection", "Refresh page", "Try saving again", "Contact support if issue persists"] },
        { type: "h3", text: "Images Not Loading" },
        { type: 'p', text: "**If images don't display:**" },
        { type: 'ul', items: ["Check file size (< 5MB)", "Try different format (JPG vs PNG)", "Re-upload image", "Clear browser cache"] },
        { type: "h3", text: "Layout Issues" },
        { type: 'p', text: "**If design looks broken:**" },
        { type: 'ul', items: ["Refresh the page", "Try different browser", "Clear browser cache", "Contact support"] },
      ] },
      { heading: "Keyboard Shortcuts", blocks: [
        { type: "h3", text: "Quick Editing Tips" },
        { type: 'p', text: "**Ctrl/Cmd + Z:** Undo last change **Ctrl/Cmd + S:** Save changes **Ctrl/Cmd + A:** Select all **Delete:** Remove selected element" },
      ] },
      { heading: "Common Tasks", blocks: [
        { type: "h3", text: "Blog Post Publishing" },
        { type: 'ul', items: ["Click \"Add New Page\"", "Choose \"Blog Post\" template", "Enter title", "Write content", "Add featured image", "Set publish date", "Click \"Publish\""] },
        { type: "h3", text: "Adding a Testimonial" },
        { type: 'ul', items: ["Go to Testimonials page", "Click \"Add Testimonial\"", "Enter customer name", "Enter testimonial text", "Add photo (optional)", "Set rating", "Save"] },
        { type: "h3", text: "Updating Business Hours" },
        { type: 'ul', items: ["Go to Contact page", "Find hours section", "Click to edit", "Update hours", "Save"] },
        { type: "h3", text: "Adding a Photo Gallery" },
        { type: 'ul', items: ["Click \"Add Element\"", "Choose \"Gallery\"", "Upload photos", "Arrange order", "Set descriptions", "Save"] },
      ] },
      { heading: "Getting Help", blocks: [
        { type: "h3", text: "Built-In Help" },
        { type: 'ul', items: ["**Help button** in editor (top right)", "**Video tutorials** for common tasks", "**Tooltips** hover over elements"] },
        { type: "h3", text: "Support" },
        { type: 'p', text: "**For editing help:**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953"] },
        { type: 'p', text: "**We can help with:**" },
        { type: 'ul', items: ["Complex edits", "Design changes", "Content updates", "Troubleshooting"] },
      ] },
    ],
    faqs: [
      ["Can I edit my website anytime?", "Yes! 24/7 access to edit your site."],
      ["Are my changes live immediately?", "Yes! Most changes go live instantly."],
      ["Can I schedule content?", "Yes! Schedule blog posts and updates."],
      ["Can I undo changes?", "Yes! Use Ctrl+Z to undo."],
      ["Can you help me edit?", "Yes! We can make changes for you (additional fee)."],
      ["Is my site protected?", "Yes! Daily backups and security monitoring."]
    ],
    related: [["Getting Started", "/help/getting-started/"], ["SEO & Marketing", "/help/seo-and-marketing/"], ["Adding Blog Posts", "/help/seo-and-marketing/"]],
  },
  "domains-and-email": {
    title: "Domains & Email Setup Guide",
    metaTitle: "Domains & Email - Setup Custom Domain & Professional Email",
    metaDesc: "Complete guide to connecting your custom domain and setting up professional email accounts with your MatjarX website.",
    heroImage: { src: '/services/email-marketing.webp', alt: 'A business email account set up alongside a website', width: 1190, height: 980 },
    sections: [
      { heading: "About Domains", blocks: [
        { type: "h3", text: "What is a Domain?" },
        { type: 'p', text: "A domain is your website address (e.g., yourcompany.com)" },
        { type: 'p', text: "**Types of domains:**" },
        { type: 'ul', items: [".com.pk (Pakistani domain)", ".pk (Pakistan)", ".com (International)", ".co (International)"] },
        { type: 'p', text: "**Available domains:** Most domains available for registration" },
      ] },
      { heading: "Getting a Domain", blocks: [
        { type: "h3", text: "Option 1: We Register For You" },
        { type: 'p', text: "**If you don't have a domain:**" },
        { type: 'ul', items: ["During signup: \"I need a domain\"", "Choose domain name", "We register it for you", "Included in setup fee", "Domain is yours"] },
        { type: 'p', text: "**Included:**" },
        { type: 'ul', items: ["First year registration", "Automatic renewal", "Privacy protection", "Management through your account"] },
        { type: "h3", text: "Option 2: You Already Have One" },
        { type: 'p', text: "**If you own a domain:**" },
        { type: 'ul', items: ["Keep your current domain", "We connect it to your site", "Takes 24-48 hours to activate", "No additional charge"] },
        { type: 'p', text: "**We'll guide you through connection process**" },
        { type: "h3", text: "Option 3: Transfer Your Domain" },
        { type: 'p', text: "**If domain is at another provider:**" },
        { type: 'ul', items: ["Unlock domain with current host", "Get transfer code", "We handle transfer", "Domain moves to us", "Continues with your site"] },
        { type: 'p', text: "**Transfer is seamless—your site stays live**" },
      ] },
      { heading: "Connecting Your Custom Domain", blocks: [
        { type: "h3", text: "Step-by-Step Connection Guide" },
        { type: 'p', text: "**You have:**" },
        { type: 'ul', items: ["Your MatjarX website", "A custom domain (owned or registered elsewhere)"] },
        { type: 'p', text: "**Goal:** Connect them" },
        { type: "h3", text: "If We Registered Your Domain" },
        { type: 'p', text: "**It's already connected!** No action needed." },
        { type: 'p', text: "Your website works immediately:" },
        { type: 'ul', items: ["yourcompany.com live and working", "Email working", "All set"] },
        { type: "h3", text: "If You're Connecting Existing Domain" },
        { type: 'p', text: "**Step 1: Unlock Your Domain**" },
        { type: 'ul', items: ["Log into your current domain provider", "Find \"Unlock Domain\" option", "Unlock it (prevents unauthorized transfer)"] },
        { type: 'p', text: "**Step 2: Get Transfer Code**" },
        { type: 'ul', items: ["In current provider account", "Find \"Auth Code\" or \"EPP Code\"", "Copy the code"] },
        { type: 'p', text: "**Step 3: Initiate Transfer**" },
        { type: 'ul', items: ["In MatjarX account", "Go to \"Domains\"", "Click \"Transfer Domain\"", "Enter domain name", "Paste transfer code", "Confirm"] },
        { type: 'p', text: "**Step 4: Authorization**" },
        { type: 'ul', items: ["Email sent to domain registrant", "Click confirmation link in email", "Approve transfer"] },
        { type: 'p', text: "**Step 5: Activation**" },
        { type: 'ul', items: ["Takes 24-48 hours", "You'll receive email when complete", "Domain now points to MatjarX", "Website accessible via your domain"] },
        { type: "h3", text: "If You Just Want to Point Domain" },
        { type: 'p', text: "**If you want to keep domain elsewhere, just point it to us:**" },
        { type: 'ul', items: ["In MatjarX: \"Domains\" → \"Point Domain\"", "We provide nameserver details", "In your domain provider account: Update nameservers", "Takes 24-48 hours to activate", "Website accessible via your domain"] },
      ] },
      { heading: "Email Accounts", blocks: [
        { type: "h3", text: "Setting Up Professional Email" },
        { type: "h3", text: "What's Included" },
        { type: 'p', text: "**Launch Plan:** 5 email accounts **Boost Plan:** 10 email accounts **Growth Plan:** 15 email accounts **Platinum Plan:** 25 email accounts **Custom:** As needed" },
        { type: "h3", text: "Creating Email Accounts" },
        { type: 'p', text: "**To create an email account:**" },
        { type: 'ul', items: ["Go to \"Domains\" in your account", "Click \"Email Accounts\"", "Click \"Add Email\"", "Enter email name (e.g., \"sales\")", "Full email: sales@yourcompany.com", "Set password", "Save"] },
        { type: 'p', text: "**Email is instantly active**" },
        { type: "h3", text: "Accessing Your Email" },
        { type: 'p', text: "**Via Webmail (browser):**" },
        { type: 'ul', items: ["Go to mail.matjarx.com", "Enter your email address", "Enter password", "Webmail opens", "Send/receive emails"] },
        { type: 'p', text: "**Or use email client:**" },
        { type: 'ul', items: ["Outlook", "Gmail", "Apple Mail", "Thunderbird"] },
        { type: "h3", text: "Email Client Setup" },
        { type: 'p', text: "**To add email to Outlook/Gmail/etc:**" },
        { type: 'p', text: "**IMAP Settings:**" },
        { type: 'ul', items: ["Server: mail.matjarx.com", "Port: 993", "Security: SSL/TLS", "Username: your email address", "Password: your password"] },
        { type: 'p', text: "**SMTP Settings:**" },
        { type: 'ul', items: ["Server: mail.matjarx.com", "Port: 465", "Security: SSL/TLS", "Username: your email address", "Password: your password"] },
        { type: "h3", text: "Common Email Accounts to Create" },
        { type: 'p', text: "**sales@yourcompany.com** For sales inquiries and communications" },
        { type: 'p', text: "**support@yourcompany.com** For customer support" },
        { type: 'p', text: "**info@yourcompany.com** General inquiries" },
        { type: 'p', text: "**contact@yourcompany.com** Contact form submissions" },
        { type: 'p', text: "**noreply@yourcompany.com** Automated notifications" },
      ] },
      { heading: "Email Best Practices", blocks: [
        { type: "h3", text: "Professional Email Tips" },
        { type: 'p', text: "**Use professional addresses:**" },
        { type: 'ul', items: ["✅ john@company.com", "❌ john123@company.com", "❌ j-smith@company.com (too informal)"] },
        { type: 'p', text: "**Set signature:**" },
        { type: 'ul', items: ["Include your name", "Company name", "Phone number", "Website link"] },
        { type: 'p', text: "**Organize folders:**" },
        { type: 'ul', items: ["Inbox, Sent, Drafts (default)", "Create folders by topic", "Archive old emails", "Keep inbox clean"] },
        { type: 'p', text: "**Security:**" },
        { type: 'ul', items: ["Use strong password", "Don't share password", "Use two-factor auth (if available)", "Log out of public computers"] },
      ] },
      { heading: "Domain Management", blocks: [
        { type: "h3", text: "Renewing Your Domain" },
        { type: 'p', text: "**Domains renew automatically** yearly" },
        { type: 'p', text: "**Renewal dates:**" },
        { type: 'ul', items: ["You're notified 30 days before", "Charged automatically on renewal date", "Cost: ~PKR 1,500-3,500/year depending on domain"] },
        { type: 'p', text: "**To manage renewal:**" },
        { type: 'ul', items: ["Go to \"Domains\"", "Click domain name", "View renewal date", "Auto-renewal enabled by default"] },
        { type: "h3", text: "Changing Domain" },
        { type: 'p', text: "**To change your domain:**" },
        { type: 'ul', items: ["Register or connect new domain", "In MatjarX: \"Domains\" → \"Change Domain\"", "Select new domain", "Confirm change", "Website updates to use new domain"] },
        { type: 'p', text: "**Old domain can be kept or dropped**" },
      ] },
      { heading: "DNS & Advanced Settings", blocks: [
        { type: "h3", text: "What is DNS?" },
        { type: 'p', text: "DNS (Domain Name System) points your domain to your website." },
        { type: 'p', text: "**For most users:** Everything is automatic" },
        { type: 'p', text: "**For advanced users:** We provide DNS details for custom configurations" },
        { type: "h3", text: "DNS Records" },
        { type: 'p', text: "**Standard DNS records:**" },
        { type: 'ul', items: ["A Record: Points domain to server", "MX Record: Points email to email server", "CNAME Record: Aliases and subdomains"] },
        { type: 'p', text: "**If you need custom DNS:**" },
        { type: 'ul', items: ["Go to \"Domains\" → \"DNS\"", "View current DNS records", "Contact support for changes"] },
        { type: "h3", text: "Subdomains" },
        { type: 'p', text: "**To create subdomain (e.g., blog.yourcompany.com):**" },
        { type: 'ul', items: ["Go to \"Domains\"", "Click \"Add Subdomain\"", "Enter subdomain name", "Save", "Subdomain created"] },
      ] },
      { heading: "Troubleshooting", blocks: [
        { type: "h3", text: "Domain Not Working" },
        { type: 'p', text: "**If your domain doesn't connect:**" },
        { type: 'ul', items: ["Check domain is registered", "Wait 48 hours (DNS propagation)", "Try different browser/device", "Clear browser cache", "Contact support if still not working"] },
        { type: "h3", text: "Email Not Working" },
        { type: 'p', text: "**If you can't access email:**" },
        { type: 'ul', items: ["Check email address is created", "Verify password is correct", "Try webmail (mail.matjarx.com)", "Check with email client settings", "Contact support"] },
        { type: "h3", text: "Slow Email or Delivery Issues" },
        { type: 'ul', items: ["Check internet connection", "Try different email client", "Clear browser cache", "Contact support if issue persists"] },
      ] },
      { heading: "Security", blocks: [
        { type: "h3", text: "Protecting Your Domain & Email" },
        { type: 'p', text: "**Best practices:**" },
        { type: 'ul', items: ["✅ Use strong password (12+ chars, mix of letters/numbers/symbols)", "✅ Enable two-factor auth if available", "✅ Don't share email credentials", "✅ Keep password private", "✅ Log out of shared computers", "✅ Update password periodically"] },
        { type: "h3", text: "Email Security" },
        { type: 'p', text: "**Be careful:**" },
        { type: 'ul', items: ["Don't open suspicious attachments", "Don't click links from unknown senders", "Verify sender before replying", "Use official domain email only (not personal emails)"] },
      ] },
      { heading: "Support", blocks: [
        { type: 'p', text: "**Domain or email questions?**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["Can I have multiple domains?", "Yes! Connect multiple domains to different sites or same site."],
      ["Can I transfer my domain to another provider later?", "Yes! Domains are yours. You can transfer anytime."],
      ["How much does a domain cost?", "~PKR 1,500-3,500/year depending on domain type. First year often included."],
      ["How many email accounts can I create?", "Depends on your plan (5-25 accounts included)."],
      ["Can I add more email accounts?", "Yes! Additional accounts at ~PKR 500/month each."],
      ["Can I rename an email account?", "No, but you can create new one and delete old one."],
      ["Can I delete an email account?", "Yes! Go to Email Accounts → Delete. All emails in that account are deleted."]
    ],
    related: [["Getting Started", "/help/getting-started/"], ["Website Editor", "/help/website-editor/"], ["Billing & Plans", "/help/billing-and-plans/"]],
  },
  "billing-and-plans": {
    title: "Billing & Plans Guide",
    metaTitle: "Billing & Plans - Manage, Cancel, Switch, & Refund Policy",
    metaDesc: "Understand your MatjarX plan, manage billing, switch plans, cancel anytime, and learn our refund policy. Transparent pricing, no surprises.",
    sections: [
      { heading: "Understanding Your Plan", blocks: [
        { type: "h3", text: "What's Included in Your Plan" },
        { type: "h4", text: "Launch Plan (PKR 4,500/month)" },
        { type: 'ul', items: ["5-10 pages", "Domain included (1 year)", "Professional design", "Hosting and maintenance", "Email support", "Setup fee: PKR 22,500"] },
        { type: "h4", text: "Boost Plan (PKR 15,600/month)" },
        { type: 'ul', items: ["30 pages", "1 blog post per month", "SEO optimization", "VIP phone support (1 call/month)", "Monthly reports", "Setup fee: PKR 22,500"] },
        { type: "h4", text: "Growth Plan (PKR 27,000/month)" },
        { type: 'ul', items: ["50 pages", "3 blog posts per month", "Dedicated marketing expert", "Monthly strategy calls", "Unlimited phone support", "Setup fee: PKR 22,500"] },
        { type: "h4", text: "Platinum Plan (PKR 55,000/month)" },
        { type: 'ul', items: ["Unlimited pages and products", "10 blog posts per month", "20 social designs per month", "Ad campaign management", "Full team support", "Setup fee: PKR 140,000"] },
      ] },
      { heading: "Billing Cycle", blocks: [
        { type: "h3", text: "When You're Charged" },
        { type: 'p', text: "**First Invoice:**" },
        { type: 'ul', items: ["Setup fee (one-time)", "First month's service"] },
        { type: 'p', text: "**Monthly Invoices:**" },
        { type: 'ul', items: ["Charged on the same day each month", "Same billing date as signup", "Invoice emailed before charge"] },
        { type: "h3", text: "Payment Methods" },
        { type: 'p', text: "**Accepted:** Bank transfer only" },
        { type: 'p', text: "**How to pay:**" },
        { type: 'ul', items: ["Receive invoice via email", "Transfer amount to provided account", "Include invoice number in transfer", "Confirmation sent within 24 hours"] },
        { type: "h3", text: "Grace Period" },
        { type: 'ul', items: ["5-day grace period for overdue invoices", "After 5 days: Services may be suspended", "Pay to reactivate immediately"] },
      ] },
      { heading: "Managing Your Plan", blocks: [
        { type: "h3", text: "How to Change Your Plan" },
        { type: 'p', text: "**From your dashboard:**" },
        { type: 'ul', items: ["Go to \"Account Settings\"", "Click \"Billing & Plans\"", "Choose \"Upgrade\" or \"Downgrade\"", "Select new plan", "Confirm changes"] },
        { type: 'p', text: "**New pricing applies** on your next billing date (or immediately for upgrades)" },
        { type: "h3", text: "Upgrading Your Plan" },
        { type: 'p', text: "**When you upgrade:**" },
        { type: 'ul', items: ["New features activate immediately", "Higher pricing takes effect next billing cycle", "OR Pro-rata charge if you want features now"] },
        { type: 'p', text: "**Plans you can upgrade to:**" },
        { type: 'ul', items: ["Launch → Boost, Growth, Platinum", "Boost → Growth, Platinum", "Growth → Platinum", "Any plan → Custom"] },
        { type: "h3", text: "Downgrading Your Plan" },
        { type: 'p', text: "**When you downgrade:**" },
        { type: 'ul', items: ["Downgrade takes effect next billing cycle", "Current plan continues until renewal", "You won't lose any pages or content (if new plan accommodates)"] },
        { type: 'p', text: "**Things to know:**" },
        { type: 'ul', items: ["Some features may not be available in lower plan", "Excess pages can be archived", "Blog posts can be downloaded"] },
        { type: 'p', text: "**Example:** Downgrading from Growth (50 pages) to Boost (30 pages):" },
        { type: 'ul', items: ["Choose which 30 pages to keep", "Archive other 20 pages", "Adjust blog frequency (3/month → 1/month)"] },
      ] },
      { heading: "Annual Payment & Savings", blocks: [
        { type: "h3", text: "Pay Yearly & Save" },
        { type: 'p', text: "**Annual Payment Option:**" },
        { type: 'ul', items: ["Pay 12 months upfront", "Save 1 month (equivalent)", "Receive PKR 27,000+ discount (depending on plan)"] },
        { type: 'p', text: "**Two-Year Payment Option:**" },
        { type: 'ul', items: ["Pay 24 months upfront", "Save 6 months (equivalent)", "Receive PKR 81,000+ discount"] },
        { type: 'p', text: "**How to switch to annual billing:**" },
        { type: 'ul', items: ["Go to \"Billing Settings\"", "Choose \"Annual Payment\"", "Pay upfront", "Automatic renewal yearly"] },
      ] },
      { heading: "Cancellation", blocks: [
        { type: "h3", text: "How to Cancel Your Plan" },
        { type: 'p', text: "**To cancel:**" },
        { type: 'ul', items: ["Email office@matjarx.com", "Subject: \"Plan Cancellation\"", "Provide 30 days written notice", "State your cancellation date"] },
        { type: 'p', text: "**What happens:**" },
        { type: 'ul', items: ["Services remain active for 30 days", "Your website stays live", "Access continues until cancellation date", "No refund for remaining period"] },
        { type: "h3", text: "After Cancellation" },
        { type: 'p', text: "**Your website:**" },
        { type: 'ul', items: ["Remains live for 30 days", "After 30 days: Taken offline", "Can be migrated to another provider", "Files can be exported"] },
        { type: "h3", text: "Data After Cancellation" },
        { type: 'p', text: "After cancellation:" },
        { type: 'ul', items: ["30 days: Active and accessible", "90 days: Backup stored", "1 year: May be permanently deleted"] },
        { type: 'p', text: "**Export your data** before cancellation deadline if you plan to use elsewhere" },
      ] },
      { heading: "Refund Policy", blocks: [
        { type: "h3", text: "Setup Fees" },
        { type: 'p', text: "**Setup fees are non-refundable once work starts**" },
        { type: 'p', text: "However:" },
        { type: 'ul', items: ["Within 24 hours of payment", "If no work has begun", "Full refund available"] },
        { type: 'p', text: "**After 24 hours or once work starts:** Non-refundable" },
        { type: "h3", text: "Monthly Subscriptions" },
        { type: 'p', text: "**Monthly subscriptions are non-refundable** once the billing cycle begins" },
        { type: 'p', text: "You can cancel anytime with 30 days notice (services remain active during notice period)" },
        { type: "h3", text: "Custom Projects" },
        { type: 'p', text: "**Refunds considered for:**" },
        { type: 'ul', items: ["Significant dissatisfaction", "Work doesn't meet specs", "Approval hasn't been given"] },
        { type: 'p', text: "**Deductions applied for:**" },
        { type: 'ul', items: ["Time and labor invested", "Assets purchased", "Tools and resources", "Operational costs"] },
        { type: 'p', text: "Remaining balance refunded within 30 days" },
        { type: "h3", text: "Non-Refundable Items" },
        { type: 'ul', items: ["❌ Domain purchases", "❌ Hosting fees", "❌ Third-party plugins/tools", "❌ Completed and approved work", "❌ Blog posts already delivered", "❌ SEO work performed"] },
      ] },
      { heading: "Payment Issues", blocks: [
        { type: "h3", text: "What if my payment fails?" },
        { type: 'p', text: "**If your bank transfer doesn't go through:**" },
        { type: 'ul', items: ["Check the account details in your invoice", "Verify amount and reference number", "Try the transfer again", "Contact your bank for issues"] },
        { type: 'p', text: "**If payment is unsuccessful after 5 days:**" },
        { type: 'ul', items: ["Services may be suspended", "You'll receive reminder emails", "Make payment to reactivate"] },
        { type: "h3", text: "Disputing a Charge" },
        { type: 'p', text: "**If you believe you were charged incorrectly:**" },
        { type: 'ul', items: ["Email office@matjarx.com", "Provide invoice number and details", "Explain the issue", "We'll review within 48 hours"] },
        { type: "h3", text: "Payment Plans" },
        { type: 'p', text: "**Flexible payment options available:**" },
        { type: 'ul', items: ["Full upfront (discount available)", "50/50 (half upfront, half on launch)", "Milestone-based payments", "Monthly payment plan (discuss with sales)"] },
      ] },
      { heading: "Annual Billing Summary", blocks: [
        { type: "h3", text: "Your Annual Costs" },
        { type: 'p', text: "**Launch Plan (Annual):**" },
        { type: 'ul', items: ["Setup: PKR 22,500", "Monthly: PKR 54,000 (12 × PKR 4,500)", "Total: PKR 76,500", "With annual discount: PKR 67,500 (save PKR 9,000)"] },
        { type: 'p', text: "**Boost Plan (Annual):**" },
        { type: 'ul', items: ["Setup: PKR 22,500", "Monthly: PKR 187,200 (12 × PKR 15,600)", "Total: PKR 209,700", "With annual discount: PKR 194,100 (save PKR 15,600)"] },
        { type: 'p', text: "**Growth Plan (Annual):**" },
        { type: 'ul', items: ["Setup: PKR 22,500", "Monthly: PKR 324,000 (12 × PKR 27,000)", "Total: PKR 346,500", "With annual discount: PKR 319,500 (save PKR 27,000)"] },
        { type: 'p', text: "**Platinum Plan (Annual):**" },
        { type: 'ul', items: ["Setup: PKR 140,000", "Monthly: PKR 660,000 (12 × PKR 55,000)", "Total: PKR 800,000", "With annual discount: PKR 745,000 (save PKR 55,000)"] },
      ] },
      { heading: "Your Invoice", blocks: [
        { type: "h3", text: "Understanding Your Invoice" },
        { type: 'p', text: "Your invoice includes:" },
        { type: 'ul', items: ["Invoice number (for reference)", "Invoice date", "Due date", "Services provided", "Amount due", "Payment instructions", "Account information"] },
        { type: 'p', text: "**Keep your invoices** for tax and record purposes" },
      ] },
      { heading: "Support", blocks: [
        { type: 'p', text: "**Questions about billing?**" },
        { type: 'ul', items: ["**Email:** office@matjarx.com", "**WhatsApp:** +92 303 372 0953", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["When am I charged?", "Setup fee at signup. Then monthly on your billing date (same day each month)."],
      ["Can I switch plans mid-month?", "Yes. New pricing takes effect next billing cycle (or immediately if upgrading)."],
      ["What if I want to cancel?", "Anytime with 30 days written notice. Your site stays live during notice period."],
      ["Can I get a refund?", "Setup fees aren't refundable once work starts. Monthly subscriptions aren't refundable. See full refund policy for details."],
      ["Do you accept credit cards?", "No. Bank transfer only. We'll send you transfer details in your invoice."],
      ["Can I pay differently?", "Discuss payment plans with our sales team. Flexible options available."],
      ["What if I'm dissatisfied?", "We focus on your satisfaction. Discuss concerns with your account manager."]
    ],
    related: [["Plans & Pricing", "/plans/"], ["Getting Started", "/help/getting-started/"], ["Refund Policy", "/refund-policy/"], ["Terms & Conditions", "/terms-and-conditions/"]],
  },
  "ecommerce-and-payments": {
    title: "E-Commerce & Payments Guide",
    metaTitle: "E-Commerce & Payments - Accept Payments Online & Gateways",
    metaDesc: "Learn to accept payments on your MatjarX website. Payment gateway setup, JazzCash integration, and online transaction processing.",
    heroImage: { src: '/help/ecommerce-payments.webp', alt: 'An online store checkout with a shopping cart, ready to ship', width: 1190, height: 980 },
    sections: [
      { heading: "E-Commerce Features", blocks: [
        { type: "h3", text: "Who Needs E-Commerce?" },
        { type: 'p', text: "**You need e-commerce if you:**" },
        { type: 'ul', items: ["Sell physical products", "Sell digital products", "Charge for services online", "Run a subscription business", "Accept donations"] },
        { type: 'p', text: "**Available on:** Platinum Plan (unlimited products)" },
      ] },
      { heading: "Setting Up Your Online Store", blocks: [
        { type: "h3", text: "Getting Started With E-Commerce" },
        { type: 'p', text: "**Step 1: Enable E-Commerce**" },
        { type: 'ul', items: ["You're on Platinum Plan (e-commerce enabled)", "Go to \"Settings\" → \"E-Commerce\"", "Enable online store", "Configure store settings"] },
        { type: 'p', text: "**Step 2: Add Products**" },
        { type: 'ul', items: ["Click \"Add Product\"", "Enter product name", "Set price", "Add product description", "Upload product images", "Configure variants (if applicable)", "Set inventory levels", "Save product"] },
        { type: 'p', text: "**Step 3: Organize Products**" },
        { type: 'ul', items: ["Create product categories", "Sort products by category", "Set featured products", "Arrange display order"] },
        { type: 'p', text: "**Step 4: Setup Payment**" },
        { type: 'ul', items: ["Choose payment gateway", "Configure payment method", "Set up account", "Test transactions"] },
        { type: 'p', text: "**Step 5: Launch Store**" },
        { type: 'ul', items: ["Review all products", "Check pricing", "Test shopping cart", "Go live"] },
      ] },
      { heading: "Payment Gateways", blocks: [
        { type: "h3", text: "What is a Payment Gateway?" },
        { type: 'p', text: "A payment gateway lets customers pay you online safely." },
        { type: 'p', text: "**Multiple gateways supported:**" },
        { type: 'ul', items: ["JazzCash", "Bank Transfers", "Other Pakistani payment providers (contact for details)"] },
        { type: "h3", text: "Choosing a Payment Gateway" },
        { type: 'p', text: "**Factors to consider:**" },
        { type: 'ul', items: ["Transaction fees", "Settlement time", "Customer convenience", "Setup complexity", "Security"] },
      ] },
      { heading: "JazzCash Integration", blocks: [
        { type: "h3", text: "What is JazzCash?" },
        { type: 'p', text: "JazzCash is a popular Pakistani mobile payment service." },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["Easy for customers (many Pakistanis use JazzCash)", "Fast setup", "Reliable payments", "Good settlement"] },
        { type: "h3", text: "Setting Up JazzCash" },
        { type: 'p', text: "**Prerequisites:**" },
        { type: 'ul', items: ["JazzCash merchant account", "Merchant ID", "API credentials"] },
        { type: 'p', text: "**Setup steps:**" },
        { type: 'p', text: "**Step 1: Get JazzCash Account**" },
        { type: 'ul', items: ["Visit jazz.com.pk", "Apply for merchant account", "Provide business details", "Get approval (typically 2-3 days)", "Receive merchant credentials"] },
        { type: 'p', text: "**Step 2: Configure in MatjarX**" },
        { type: 'ul', items: ["Go to \"Settings\" → \"Payment\"", "Click \"JazzCash\"", "Enter merchant ID", "Enter API key", "Save configuration"] },
        { type: 'p', text: "**Step 3: Test Payment**" },
        { type: 'ul', items: ["Add test product", "Test checkout process", "Complete test payment", "Verify it processes correctly", "Remove test product"] },
        { type: 'p', text: "**Step 4: Go Live**" },
        { type: 'ul', items: ["Remove test mode", "Monitor first transactions", "Ensure payments processing", "Confirm settlement"] },
        { type: "h3", text: "JazzCash Settlement" },
        { type: 'p', text: "**How you get paid:**" },
        { type: 'p', text: "**Payments received** → **JazzCash holds funds** → **Settlement to your account**" },
        { type: 'p', text: "**Settlement timeline:** Typically 2-3 business days" },
        { type: 'p', text: "**Settlement account:**" },
        { type: 'ul', items: ["Bank account linked to JazzCash", "Funds transferred automatically", "Check JazzCash dashboard for status"] },
      ] },
      { heading: "Bank Transfer Payments", blocks: [
        { type: "h3", text: "Direct Bank Transfers" },
        { type: 'p', text: "**If customers pay by bank transfer:**" },
        { type: 'ul', items: ["Enable bank transfer option", "Provide your account details", "Customer transfers payment", "You manually confirm order", "Send confirmation to customer"] },
        { type: 'p', text: "**Setup:**" },
        { type: 'ul', items: ["Go to \"Settings\" → \"Payment\"", "Click \"Bank Transfer\"", "Enter your account details:", "Account name", "Account number", "Bank name", "Branch code (if applicable)", "Save"] },
        { type: "h3", text: "Managing Bank Transfers" },
        { type: 'p', text: "**When payment received:**" },
        { type: 'ul', items: ["Check your bank account", "Confirm order in MatjarX", "Send order confirmation to customer", "Process shipment or delivery"] },
      ] },
      { heading: "Products & Inventory", blocks: [
        { type: "h3", text: "Adding Products" },
        { type: 'p', text: "**Complete product information:**" },
        { type: 'p', text: "**Basic Details:**" },
        { type: 'ul', items: ["Product name", "Price", "Currency (PKR)", "Availability (in stock / out of stock)"] },
        { type: 'p', text: "**Description:**" },
        { type: 'ul', items: ["What the product is", "Key features", "Benefits", "Specifications"] },
        { type: 'p', text: "**Images:**" },
        { type: 'ul', items: ["Multiple photos from different angles", "High quality (at least 800x800 px)", "Upload 3-5 images per product"] },
        { type: 'p', text: "**Categories:**" },
        { type: 'ul', items: ["Assign to relevant category", "For organization and filtering"] },
        { type: 'p', text: "**Variants (Optional):**" },
        { type: 'ul', items: ["Size, Color, Version, etc.", "Set different prices per variant", "Track inventory per variant"] },
        { type: 'p', text: "**SEO:**" },
        { type: 'ul', items: ["Product SEO title", "Product description for search", "Keywords"] },
        { type: "h3", text: "Managing Inventory" },
        { type: 'p', text: "**Setting stock levels:**" },
        { type: 'ul', items: ["Edit product", "Set quantity in stock", "Save", "Inventory decreases as customers order"] },
        { type: 'p', text: "**Low stock alerts:**" },
        { type: 'ul', items: ["Notified when items running low", "Can set low stock threshold", "Reorder before out of stock"] },
        { type: 'p', text: "**Out of stock:**" },
        { type: 'ul', items: ["Product marked unavailable", "Customers can't purchase", "Can re-enable when restocked"] },
      ] },
      { heading: "Shopping Cart & Checkout", blocks: [
        { type: "h3", text: "Cart Experience" },
        { type: 'p', text: "**Customers can:**" },
        { type: 'ul', items: ["Add products to cart", "Update quantities", "Remove items", "View cart total", "See shipping cost (if applicable)"] },
        { type: 'p', text: "**You can customize:**" },
        { type: 'ul', items: ["Cart page layout", "Checkout flow", "Required information", "Payment options"] },
        { type: "h3", text: "Checkout Process" },
        { type: 'p', text: "**Customer journey:**" },
        { type: 'ul', items: ["Browse products", "Add to cart", "Review cart", "Enter shipping details", "Select shipping method", "Choose payment method", "Complete payment", "Order confirmation"] },
        { type: "h3", text: "Order Information Collection" },
        { type: 'p', text: "**You can collect:**" },
        { type: 'ul', items: ["Customer name", "Shipping address", "Phone number", "Email address", "Special instructions", "Custom fields (optional)"] },
      ] },
      { heading: "Managing Orders", blocks: [
        { type: "h3", text: "Viewing Orders" },
        { type: 'p', text: "**In your dashboard:**" },
        { type: 'ul', items: ["Go to \"Orders\"", "See all customer orders", "Click order to view details", "See customer and product info"] },
        { type: "h3", text: "Order Status" },
        { type: 'p', text: "**Track order status:**" },
        { type: 'ul', items: ["Pending (payment received, not yet shipped)", "Processing (preparing to ship)", "Shipped (sent to customer)", "Delivered (customer received)", "Cancelled", "Refunded"] },
        { type: "h3", text: "Updating Customers" },
        { type: 'p', text: "**Send order updates:**" },
        { type: 'ul', items: ["Customer places order", "Automatic confirmation email", "When shipping: send tracking info", "Upon delivery: send delivery confirmation", "Any issues: contact customer immediately"] },
        { type: "h3", text: "Handling Issues" },
        { type: 'p', text: "**Out of stock:**" },
        { type: 'ul', items: ["Refund customer immediately", "Send apology + explanation", "Offer replacement product or reschedule"] },
        { type: 'p', text: "**Damaged product:**" },
        { type: 'ul', items: ["Customer reports damage", "Process refund", "Arrange replacement shipment", "Send prepaid return label"] },
        { type: 'p', text: "**Wrong product:**" },
        { type: 'ul', items: ["Process return quickly", "Send correct product", "Cover return shipping", "Rebuild customer trust"] },
      ] },
      { heading: "Shipping", blocks: [
        { type: "h3", text: "Setting Up Shipping" },
        { type: 'p', text: "**Shipping options:**" },
        { type: 'p', text: "**Option 1: Manual Shipping**" },
        { type: 'ul', items: ["You arrange courier", "You provide tracking info", "Customer checks status themselves"] },
        { type: 'p', text: "**Option 2: Integration With Courier**" },
        { type: 'ul', items: ["Connect to TCS, Leopards, etc.", "Auto-generate labels", "Customer auto-notified", "Tracking automatic"] },
        { type: "h3", text: "Shipping Costs" },
        { type: 'p', text: "**How to charge:**" },
        { type: 'ul', items: ["Free shipping (good for retention)", "Flat rate (simple)", "Calculate per location", "Provide shipping estimates"] },
      ] },
      { heading: "Security & Compliance", blocks: [
        { type: "h3", text: "PCI Compliance" },
        { type: 'p', text: "**Payment security:**" },
        { type: 'ul', items: ["All transactions encrypted", "No credit card data stored", "Payment gateway handles security", "Regular security audits"] },
        { type: "h3", text: "Security Measures" },
        { type: 'p', text: "**Protecting customer data:**" },
        { type: 'ul', items: ["SSL/HTTPS encryption", "Secure checkout", "Data protection", "Fraud prevention"] },
        { type: "h3", text: "Privacy" },
        { type: 'p', text: "**Customer information:**" },
        { type: 'ul', items: ["Never share customer data", "Privacy policy required", "Clear data use", "GDPR compliant (for EU customers)"] },
      ] },
      { heading: "Refunds & Returns", blocks: [
        { type: "h3", text: "Processing Refunds" },
        { type: 'p', text: "**If customer requests refund:**" },
        { type: 'ul', items: ["Review refund policy", "Verify request validity", "Process refund in gateway", "Money returned to customer", "Send confirmation email"] },
        { type: 'p', text: "**Timeline:** Depends on payment gateway (typically 3-7 days)" },
        { type: "h3", text: "Return Policy" },
        { type: 'p', text: "**Best practices:**" },
        { type: 'ul', items: ["Clear return policy", "Easy return process", "Prepaid return labels (if possible)", "Refund timeline (e.g., within 7 days)"] },
      ] },
      { heading: "Analytics & Reports", blocks: [
        { type: "h3", text: "Tracking Sales" },
        { type: 'p', text: "**Dashboard shows:**" },
        { type: 'ul', items: ["Total sales (today, this week, this month)", "Number of orders", "Average order value", "Popular products", "Sales trends"] },
        { type: "h3", text: "Detailed Reports" },
        { type: 'p', text: "**Export reports:**" },
        { type: 'ul', items: ["Sales by product", "Sales by date range", "Customer information", "Payment method breakdown"] },
        { type: 'p', text: "**Use for:**" },
        { type: 'ul', items: ["Tax preparation", "Business analysis", "Growth tracking", "Inventory planning"] },
      ] },
      { heading: "Troubleshooting", blocks: [
        { type: "h3", text: "Payment Issues" },
        { type: 'p', text: "**If payment not going through:**" },
        { type: 'ul', items: ["Check payment gateway is enabled", "Verify payment account is active", "Test with small amount", "Check with your payment provider", "Contact support"] },
        { type: "h3", text: "Order Not Appearing" },
        { type: 'p', text: "**If order doesn't show:**" },
        { type: 'ul', items: ["Check order confirmation email", "Check your orders dashboard", "Verify payment processed", "Contact support"] },
        { type: "h3", text: "Customer Disputes" },
        { type: 'p', text: "**If customer disputes payment:**" },
        { type: 'ul', items: ["Review transaction details", "Check order confirmation", "Gather documentation", "Contact payment provider if needed", "Resolve with customer"] },
      ] },
      { heading: "Support", blocks: [
        { type: 'p', text: "**E-commerce or payment questions?**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["What payment methods can I accept?", "JazzCash, bank transfers, and others (contact for more options)."],
      ["How much does payment processing cost?", "Depends on gateway (typically 1-3% per transaction). Confirm with your provider."],
      ["How long until money is in my account?", "Typically 2-3 business days depending on payment method."],
      ["Can customers pay partially and later?", "Not by default, but can be configured. Contact support."],
      ["Do I need a separate merchant account?", "Yes for payment gateways like JazzCash. We'll guide you through setup."],
      ["Is customer data secure?", "Yes! PCI compliant and encrypted. We never store credit card details."]
    ],
    related: [["Website Editor", "/help/website-editor/"], ["Platinum Plan", "/plans/platinum/"], ["Getting Started", "/help/getting-started/"]],
  },
  "seo-and-marketing": {
    title: "SEO & Marketing Guide",
    metaTitle: "SEO & Marketing Help - Improve Google Rankings & Traffic",
    metaDesc: "Complete guide to improving your Google rankings and attracting customers. Local SEO, content strategy, marketing tips for MatjarX websites.",
    heroImage: { src: '/services/five-month-program.webp', alt: "Google's AI Overview describing MatjarX as an emerging website builder", width: 850, height: 538 },
    sections: [
      { heading: "Understanding SEO", blocks: [
        { type: "h3", text: "What is SEO?" },
        { type: 'p', text: "SEO (Search Engine Optimization) helps your website rank on Google so customers can find you." },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["Free traffic from Google", "Targeted visitors", "Customers actively looking for you", "Long-term results", "Builds credibility"] },
        { type: "h3", text: "Why SEO Matters" },
        { type: 'p', text: "**Most people:** Start by searching on Google **Your goal:** Appear in top results for relevant keywords **Result:** Customers find you and contact you" },
      ] },
      { heading: "On-Page SEO", blocks: [
        { type: "h3", text: "Optimizing Your Pages" },
        { type: 'p', text: "**Title Tags (60 characters):**" },
        { type: 'ul', items: ["Include main keyword", "Keep it under 60 characters", "Make it compelling", "Example: \"Best Pizza Restaurant in Karachi | Luigi's\""] },
        { type: 'p', text: "**Meta Descriptions (155 characters):**" },
        { type: 'ul', items: ["Summarize page content", "Include keyword naturally", "Keep under 155 characters", "Make it click-worthy", "Example: \"Authentic Italian pizza in Karachi. Fresh ingredients, wood-fired oven. Order online or visit us today.\""] },
        { type: 'p', text: "**Headings (H1, H2, H3):**" },
        { type: 'ul', items: ["Use one H1 per page (main title)", "Use H2s for sections", "Include keywords naturally", "Help structure content"] },
        { type: 'p', text: "**Content (300+ words):**" },
        { type: 'ul', items: ["Write substantial content (at least 300 words)", "Include keywords naturally", "Use clear language", "Answer customer questions", "Update regularly"] },
        { type: "h3", text: "Keyword Optimization" },
        { type: 'p', text: "**Finding keywords:**" },
        { type: 'ul', items: ["What would customers search for?", "\"Best [service] in [city]\"", "\"[Service] near me\"", "\"[Service] prices\"", "Use Google Keyword Planner (free)"] },
        { type: 'p', text: "**Using keywords:**" },
        { type: 'ul', items: ["Include in page title", "Include in meta description", "Use in headings", "Use in first paragraph", "Don't over-use (sounds unnatural)"] },
        { type: "h3", text: "Internal Linking" },
        { type: 'p', text: "**Link to related pages:**" },
        { type: 'ul', items: ["Helps Google understand site structure", "Helps visitors navigate", "Keeps people on your site", "Spreads authority"] },
        { type: 'p', text: "**Example:** On a blog about \"Web Design Tips,\" link to your Web Design Services page" },
      ] },
      { heading: "Technical SEO", blocks: [
        { type: "h3", text: "Site Speed" },
        { type: 'p', text: "**Why it matters:**" },
        { type: 'ul', items: ["Google ranks faster sites higher", "Visitors leave slow sites", "Affects conversion"] },
        { type: 'p', text: "**Improving speed:**" },
        { type: 'ul', items: ["Compress images", "Minimize code", "Use caching", "Remove unnecessary plugins", "Upgrade hosting (if needed)"] },
        { type: 'p', text: "**Check your speed:**" },
        { type: 'ul', items: ["Go to PageSpeed Insights", "Enter your URL", "Review recommendations", "MatjarX handles most of this"] },
        { type: "h3", text: "Mobile Optimization" },
        { type: 'p', text: "**Mobile is critical:**" },
        { type: 'ul', items: ["60%+ of searches from mobile", "Google ranks mobile-friendly sites higher", "Mobile users expect fast pages"] },
        { type: 'p', text: "**MatjarX handles:**" },
        { type: 'ul', items: ["Mobile-responsive design", "Mobile optimization", "Mobile speed", "Touch-friendly interface"] },
        { type: "h3", text: "SSL Certificate" },
        { type: 'p', text: "**HTTPS (secure connection):**" },
        { type: 'ul', items: ["Green lock icon in browser", "Protects data", "Required for payments", "Boosts SEO rankings"] },
        { type: 'p', text: "**MatjarX includes:** Free SSL certificate on all sites" },
      ] },
      { heading: "Content Strategy", blocks: [
        { type: "h3", text: "Blog Posting Strategy" },
        { type: 'p', text: "**Why blog?**" },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["New pages for Google to rank", "More keyword opportunities", "Establish authority", "Build audience", "Drive traffic", "Generate leads"] },
        { type: 'p', text: "**Included by plan:**" },
        { type: 'ul', items: ["Launch: No blog posts", "Boost: 1 blog post/month", "Growth: 3 blog posts/month", "Platinum: 10 blog posts/month"] },
        { type: "h3", text: "Blog Best Practices" },
        { type: 'p', text: "**Topic selection:**" },
        { type: 'ul', items: ["Answer customer questions", "Use keywords strategically", "Write about your expertise", "Cover topics customers search for"] },
        { type: 'p', text: "**Writing for Google:**" },
        { type: 'ul', items: ["1,000+ words per post", "Include keywords naturally", "Use clear headings", "Break into sections", "Use images", "Link to related pages"] },
        { type: 'p', text: "**Publishing strategy:**" },
        { type: 'ul', items: ["Consistent schedule", "Regular posts (at least monthly)", "Promote on social media", "Build authority over time", "Long-term strategy"] },
        { type: "h3", text: "Content Calendar" },
        { type: 'p', text: "**Plan your content:**" },
        { type: 'ul', items: ["Brainstorm topics (quarterly)", "Research keywords", "Create content calendar", "Assign authors", "Publish on schedule", "Monitor performance"] },
        { type: 'p', text: "**Example blog topics:**" },
        { type: 'p', text: "**Restaurant:**" },
        { type: 'ul', items: ["\"Best Pasta Recipes\"", "\"Italian Cooking Tips\"", "\"Food Trends 2024\""] },
        { type: 'p', text: "**Real Estate:**" },
        { type: 'ul', items: ["\"Buying Your First Home\"", "\"Market Tips by Neighborhood\"", "\"Investment Property Guide\""] },
        { type: 'p', text: "**Salon:**" },
        { type: 'ul', items: ["\"Hair Care Tips\"", "\"Seasonal Style Trends\"", "\"Bridal Hair Inspiration\""] },
      ] },
      { heading: "Local SEO", blocks: [
        { type: "h3", text: "What is Local SEO?" },
        { type: 'p', text: "Local SEO helps you rank for location-based searches (e.g., \"Dentist near me\")" },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["Rank in local search results", "Show up on Google Maps", "Attract nearby customers", "Build local presence"] },
        { type: "h3", text: "Google Business Profile" },
        { type: 'p', text: "**What it is:**" },
        { type: 'ul', items: ["Free Google listing for your business", "Shows on Google Maps", "Appears in local search", "Displays reviews, photos, hours"] },
        { type: 'p', text: "**Setup:**" },
        { type: 'ul', items: ["Go to google.com/business", "Create or claim your profile", "Add business information", "Verify your address (postcard from Google)", "Add photos", "Gather reviews"] },
        { type: "h3", text: "Local SEO Optimization" },
        { type: 'p', text: "**Business information:**" },
        { type: 'ul', items: ["Accurate name", "Complete address", "Phone number", "Email", "Website link", "Business hours", "Accurate category"] },
        { type: 'p', text: "**Photos:**" },
        { type: 'ul', items: ["Business exterior", "Interior/workspace", "Products/services", "Team photos", "Customer photos", "At least 10 photos"] },
        { type: 'p', text: "**Reviews:**" },
        { type: 'ul', items: ["Ask customers to review", "Respond to all reviews", "Thank 5-star reviewers", "Address 1-star reviews professionally", "Build review count (more = better)"] },
        { type: 'p', text: "**Citations:**" },
        { type: 'ul', items: ["List business in directories", "Google Maps", "Local business directories", "Industry-specific directories", "Facebook Business"] },
        { type: "h3", text: "Ranking Locally" },
        { type: 'p', text: "**Factors affecting local ranking:**" },
        { type: 'ul', items: ["Reviews and ratings", "Google Business Profile completeness", "Citations and consistency", "Local keyword optimization", "Proximity to searcher", "Content relevance"] },
      ] },
      { heading: "Backlink Building", blocks: [
        { type: "h3", text: "What are Backlinks?" },
        { type: 'p', text: "Backlinks are links from other websites to yours." },
        { type: 'p', text: "**Why they matter:**" },
        { type: 'ul', items: ["Signal authority to Google", "Boost rankings", "Build credibility", "Drive referral traffic"] },
        { type: "h3", text: "Building Quality Backlinks" },
        { type: 'p', text: "**Do:**" },
        { type: 'ul', items: ["✅ Write quality content worth linking to", "✅ Request links from industry partners", "✅ Submit to local business directories", "✅ Get reviews (generates backlinks)", "✅ Write guest posts", "✅ Build relationships with other sites"] },
        { type: 'p', text: "**Don't:**" },
        { type: 'ul', items: ["❌ Buy backlinks", "❌ Exchange links indiscriminately", "❌ Use link schemes", "❌ Accept links from spammy sites"] },
        { type: "h3", text: "Link Building Strategy" },
        { type: 'p', text: "**Opportunities:**" },
        { type: 'ul', items: ["Local directories (list your business)", "Industry associations (member listings)", "Sponsorships (get website link)", "Guest blogging (write for other sites)", "Media mentions (get coverage)", "Partnerships (collaborate with others)"] },
      ] },
      { heading: "Social Media & Marketing", blocks: [
        { type: "h3", text: "Social Media Strategy" },
        { type: 'p', text: "**Social media helps:**" },
        { type: 'ul', items: ["Share content", "Build audience", "Drive traffic to site", "Build brand", "Engage with customers", "Generate leads"] },
        { type: 'p', text: "**Best platforms:**" },
        { type: 'ul', items: ["Facebook (most popular in Pakistan)", "Instagram (visual content)", "LinkedIn (B2B)", "WhatsApp (direct communication)"] },
        { type: "h3", text: "Promoting Your Content" },
        { type: 'p', text: "**When you publish blog:**" },
        { type: 'ul', items: ["Share on Facebook", "Share on Instagram", "Share on LinkedIn (if B2B)", "Send email to list", "Share with network", "Encourage sharing"] },
        { type: 'p', text: "**Ongoing promotion:**" },
        { type: 'ul', items: ["Share older posts regularly", "Create graphics for posts", "Write compelling captions", "Engage with comments", "Build community"] },
        { type: "h3", text: "Email Marketing" },
        { type: 'p', text: "**Building email list:**" },
        { type: 'ul', items: ["Email capture on website", "Offer value (discount, guide, etc.)", "Regular newsletters", "Exclusive content"] },
        { type: 'p', text: "**Email strategy:**" },
        { type: 'ul', items: ["Welcome new subscribers", "Regular updates (weekly/bi-weekly)", "Promote your blog", "Share updates", "Exclusive offers", "Build relationship"] },
      ] },
      { heading: "Analytics & Tracking", blocks: [
        { type: "h3", text: "Google Analytics" },
        { type: 'p', text: "**What to track:**" },
        { type: 'ul', items: ["Traffic sources (organic, direct, referral)", "Top pages", "User behavior", "Bounce rate", "Time on page", "Conversions"] },
        { type: "h3", text: "Key Metrics" },
        { type: 'p', text: "**Organic Traffic:** Visitors from Google search **Bounce Rate:** % of visitors who leave without action **Average Time on Page:** How long people stay **Conversions:** Actions you care about (contact, purchase, etc.)" },
        { type: "h3", text: "Using Data" },
        { type: 'p', text: "**Optimize based on:**" },
        { type: 'ul', items: ["Top performing pages (create similar content)", "Pages with high bounce rate (improve or remove)", "Keywords that rank (expand content)", "Conversion data (improve conversion pages)"] },
      ] },
      { heading: "Ranking Expectations", blocks: [
        { type: "h3", text: "Timeline for Results" },
        { type: 'p', text: "**SEO is long-term:**" },
        { type: 'ul', items: ["Month 1-2: Initial ranking for easy keywords", "Month 3-4: More rankings appearing", "Month 6: Noticeable traffic increase", "Month 12: Significant traffic and leads"] },
        { type: 'p', text: "**Varies by:**" },
        { type: 'ul', items: ["Competition level", "Keyword difficulty", "Content quality", "Backlink building", "Your effort"] },
        { type: "h3", text: "Realistic Expectations" },
        { type: 'p', text: "**What we guarantee:**" },
        { type: 'ul', items: ["❌ Google ranking #1 (not guaranteed)", "❌ Specific traffic amount", "❌ X number of leads"] },
        { type: 'p', text: "**What actually happens:**" },
        { type: 'ul', items: ["✅ Rankings improve over time", "✅ Traffic gradually increases", "✅ Leads consistently grow", "✅ Long-term sustainable growth"] },
      ] },
      { heading: "Common SEO Mistakes", blocks: [
        { type: 'p', text: "**Don't do these:**" },
        { type: 'ul', items: ["❌ Keyword stuffing (overusing keyword unnaturally)", "❌ Duplicate content (copying from other sites)", "❌ Buying backlinks (violates Google rules)", "❌ Neglecting mobile (over 60% of searches)", "❌ Ignoring analytics (data-driven optimization)", "❌ Irregular posting (consistency matters)", "❌ Poor quality content (write for humans, not robots)"] },
      ] },
      { heading: "Support", blocks: [
        { type: 'p', text: "**SEO and marketing questions?**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["How long until I rank?", "2-6 months typically. Depends on competition."],
      ["How much does SEO cost?", "SEO is included in your plan (Boost+). Blog and content strategy included."],
      ["Can you guarantee #1 ranking?", "No one can. Factors beyond your control affect rankings. We focus on improvement."],
      ["Should I do paid ads?", "Paid ads (Google Ads, Facebook) work alongside organic. Good for quick results."],
      ["How often should I blog?", "Monthly at minimum. More frequent = faster results."],
      ["What keywords should I target?", "Keywords customers search for. We research keywords for you."]
    ],
    related: [["Boost Plan", "/plans/boost/"], ["Growth Plan", "/plans/growth/"], ["Website Editor", "/help/website-editor/"]],
  },
  "account-and-security": {
    title: "Account & Security Guide",
    metaTitle: "Account & Security - Password Reset, Login Help & 2FA",
    metaDesc: "Manage your MatjarX account securely. Password reset, login help, account settings, and two-factor authentication guide.",
    sections: [
      { heading: "Logging In", blocks: [
        { type: "h3", text: "How to Access Your Account" },
        { type: 'p', text: "**Go to matjarx.com:**" },
        { type: 'ul', items: ["Click \"Login\" (top right)", "Enter your email address", "Enter your password", "Click \"Login\""] },
        { type: 'p', text: "**Bookmark the login page** for easy access: matjarx.com/login" },
        { type: "h3", text: "Login Issues" },
        { type: 'p', text: "**If you can't log in:**" },
        { type: 'ul', items: ["Check email and password are correct (case-sensitive)", "Make sure Caps Lock is OFF", "Try a different browser", "Clear browser cache", "Try incognito/private mode", "Reset password if forgotten"] },
      ] },
      { heading: "Password Reset", blocks: [
        { type: "h3", text: "Forgotten Your Password?" },
        { type: 'p', text: "**To reset your password:**" },
        { type: 'p', text: "**On login page:**" },
        { type: 'ul', items: ["Click \"Forgot Password\"", "Enter your email address", "Check your email (may take a few minutes)", "Click link in email", "Enter new password", "Confirm new password", "Click \"Reset Password\"", "Login with new password"] },
        { type: "h3", text: "Password Requirements" },
        { type: 'p', text: "**Your password must:**" },
        { type: 'ul', items: ["✅ Be at least 8 characters", "✅ Include letters (A-Z, a-z)", "✅ Include numbers (0-9)", "✅ Include special characters (!@#$%^&*)"] },
        { type: 'p', text: "**Example strong password:** MyWebsite2024!" },
        { type: "h3", text: "Changing Your Password" },
        { type: 'p', text: "**To change password anytime:**" },
        { type: 'ul', items: ["Login to your account", "Go to \"Account Settings\"", "Click \"Change Password\"", "Enter current password", "Enter new password (twice)", "Click \"Update Password\""] },
      ] },
      { heading: "Account Settings", blocks: [
        { type: "h3", text: "Managing Your Account" },
        { type: 'p', text: "**In your dashboard:**" },
        { type: 'ul', items: ["Click your name (top right)", "Click \"Account Settings\""] },
        { type: "h3", text: "Personal Information" },
        { type: 'p', text: "**Edit your details:**" },
        { type: 'ul', items: ["Email address", "Full name", "Phone number", "Business name", "Business address", "Profile photo"] },
        { type: 'p', text: "**To edit:**" },
        { type: 'ul', items: ["Click field to edit", "Update information", "Click \"Save\""] },
        { type: "h3", text: "Email Address" },
        { type: 'p', text: "**Changing email:**" },
        { type: 'ul', items: ["Go to \"Account Settings\"", "Click \"Edit Email\"", "Enter new email", "Verify with confirmation email", "Done"] },
        { type: 'p', text: "**Important:** Keep email updated. We use it for account recovery and notifications." },
        { type: "h3", text: "Business Information" },
        { type: 'p', text: "**Keep updated:**" },
        { type: 'ul', items: ["Business name", "Business description", "Logo (if changed)", "Contact information", "Address"] },
        { type: 'p', text: "This helps us support you better." },
      ] },
      { heading: "Two-Factor Authentication (2FA)", blocks: [
        { type: "h3", text: "What is Two-Factor Authentication?" },
        { type: 'p', text: "2FA adds extra security by requiring two things to login:" },
        { type: 'ul', items: ["Your password", "A code from your phone"] },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["Extra security", "Protects against hacking", "Especially important if password leaked", "Recommended for all users"] },
        { type: "h3", text: "Setting Up 2FA" },
        { type: 'p', text: "**Prerequisites:**" },
        { type: 'ul', items: ["Smartphone (iPhone or Android)", "Authenticator app (Google Authenticator, Microsoft Authenticator, Authy)"] },
        { type: 'p', text: "**Setup steps:**" },
        { type: 'ul', items: ["Go to \"Account Settings\"", "Click \"Security\" or \"Two-Factor Auth\"", "Click \"Enable 2FA\"", "Download authenticator app (if not already)", "Scan QR code with app", "Enter 6-digit code from app", "Save backup codes (in safe place!)", "Confirm setup"] },
        { type: "h3", text: "Using 2FA to Login" },
        { type: 'p', text: "**When logging in:**" },
        { type: 'ul', items: ["Enter email and password (as normal)", "You'll be asked for 2FA code", "Open authenticator app", "Enter 6-digit code shown", "Click \"Verify\"", "Access granted"] },
        { type: 'p', text: "**Codes change:** New code every 30 seconds" },
        { type: "h3", text: "Backup Codes" },
        { type: 'p', text: "**If you lose phone:**" },
        { type: 'p', text: "Backup codes let you login without app." },
        { type: 'p', text: "**Keep them safe:**" },
        { type: 'ul', items: ["Write down and store securely", "Save in password manager", "Don't share with anyone", "Don't lose them"] },
        { type: 'p', text: "**If needed:**" },
        { type: 'ul', items: ["Enter email and password", "Click \"Use backup code\"", "Enter one backup code", "Access granted", "That backup code can't be reused"] },
        { type: "h3", text: "Disabling 2FA" },
        { type: 'p', text: "**If you want to disable:**" },
        { type: 'ul', items: ["Go to \"Account Settings\"", "Click \"Security\"", "Click \"Disable 2FA\"", "Confirm (you'll lose extra security)"] },
        { type: 'p', text: "**Not recommended** unless necessary" },
      ] },
      { heading: "Security Best Practices", blocks: [
        { type: "h3", text: "Protecting Your Account" },
        { type: 'p', text: "**Do:**" },
        { type: 'ul', items: ["✅ Use strong, unique password", "✅ Enable two-factor authentication", "✅ Change password every 3-6 months", "✅ Never share password", "✅ Log out of public computers", "✅ Use password manager", "✅ Keep email updated", "✅ Review login activity"] },
        { type: 'p', text: "**Don't:**" },
        { type: 'ul', items: ["❌ Share password with anyone", "❌ Use same password for multiple sites", "❌ Write password on paper", "❌ Give password to support (they never need it)", "❌ Use easy-to-guess passwords (birthdate, name)", "❌ Login on public Wi-Fi without VPN"] },
        { type: "h3", text: "Suspicious Activity" },
        { type: 'p', text: "**If you notice:**" },
        { type: 'ul', items: ["Unexpected login notifications", "Password changed but you didn't", "Account modifications you didn't make", "Unusual activity"] },
        { type: 'p', text: "**Take action immediately:**" },
        { type: 'ul', items: ["Change password", "Check email (change if hacked)", "Enable 2FA", "Review connected apps", "Contact support"] },
        { type: "h3", text: "Password Managers" },
        { type: 'p', text: "**Recommended:** Use password manager" },
        { type: 'p', text: "**Benefits:**" },
        { type: 'ul', items: ["Remember all passwords", "Generate strong passwords", "Secure storage", "Sync across devices"] },
        { type: 'p', text: "**Popular options:**" },
        { type: 'ul', items: ["LastPass", "1Password", "Dashlane", "Bitwarden (free)"] },
      ] },
      { heading: "Session Management", blocks: [
        { type: "h3", text: "Login Sessions" },
        { type: 'p', text: "**Your session is when you're logged in**" },
        { type: 'p', text: "**To see active sessions:**" },
        { type: 'ul', items: ["Go to \"Account Settings\"", "Click \"Active Sessions\"", "View all logged-in locations/devices", "Logout from specific sessions if needed"] },
        { type: "h3", text: "Logging Out" },
        { type: 'p', text: "**To logout:**" },
        { type: 'ul', items: ["Click your name (top right)", "Click \"Logout\"", "You're logged out", "Login again to access account"] },
        { type: 'p', text: "**Tip:** Logout on public computers before leaving" },
        { type: "h3", text: "Timeout" },
        { type: 'p', text: "**For security:**" },
        { type: 'ul', items: ["Session times out after 30 days inactivity", "You'll be logged out automatically", "Login again to continue"] },
      ] },
      { heading: "Account Recovery", blocks: [
        { type: "h3", text: "If Your Account is Compromised" },
        { type: 'p', text: "**If you suspect hacking:**" },
        { type: 'p', text: "**Immediately:**" },
        { type: 'ul', items: ["Change password from secure computer", "Enable 2FA", "Review account settings", "Check connected apps", "Review recent activity"] },
        { type: 'p', text: "**Then:**" },
        { type: 'ul', items: ["Contact MatjarX support", "Provide details about suspicious activity", "We'll investigate and help secure account"] },
        { type: "h3", text: "Recovery Process" },
        { type: 'p', text: "**If locked out:**" },
        { type: 'ul', items: ["Try password reset", "Check email for reset link", "If email hacked: Contact support with proof of identity", "Verify ownership (we'll help)", "Regain access to account"] },
      ] },
      { heading: "Account Data", blocks: [
        { type: "h3", text: "Your Data" },
        { type: 'p', text: "**You own all your data:**" },
        { type: 'ul', items: ["Website content", "Customer information", "Analytics data", "Email accounts", "Domain"] },
        { type: 'p', text: "**You can:**" },
        { type: 'ul', items: ["Download your data", "Export your website", "Move to another provider", "Delete your account (and data)"] },
        { type: "h3", text: "Data Deletion" },
        { type: 'p', text: "**To permanently delete account:**" },
        { type: 'ul', items: ["Email office@matjarx.com", "Subject: \"Account Deletion Request\"", "Confirm you want deletion", "30-day waiting period", "Account and all data deleted"] },
        { type: 'p', text: "**Warning:** Deletion is permanent. Can't be undone." },
        { type: "h3", text: "Data Privacy" },
        { type: 'p', text: "**Your data is:**" },
        { type: 'ul', items: ["Secure", "Never shared", "Never sold", "Protected"] },
        { type: 'p', text: "[Read Privacy Policy →](/privacy-policy/)" },
      ] },
      { heading: "Billing Account", blocks: [
        { type: "h3", text: "Separate From Website Account" },
        { type: 'p', text: "**Two accounts:**" },
        { type: 'ul', items: ["**Website Account:** Login to edit website", "**Billing Account:** Manage subscription and payments"] },
        { type: 'p', text: "**Billing managed at:** matjarx.com/account/billing" },
        { type: "h3", text: "Payment Methods" },
        { type: 'p', text: "**Update payment method:**" },
        { type: 'ul', items: ["Go to Billing", "Click \"Payment Method\"", "Update bank details", "Save"] },
        { type: "h3", text: "Invoices" },
        { type: 'p', text: "**Access invoices:**" },
        { type: 'ul', items: ["Go to Billing", "Click \"Invoices\"", "View and download invoices", "Keep for tax records"] },
      ] },
      { heading: "Support Access", blocks: [
        { type: "h3", text: "When Support Needs Access" },
        { type: 'p', text: "**We never:**" },
        { type: 'ul', items: ["❌ Ask for passwords", "❌ Ask for 2FA codes", "❌ Ask for payment info"] },
        { type: 'p', text: "**We may:**" },
        { type: 'ul', items: ["✅ Ask to make changes for you (you grant access)", "✅ Ask permission to view account", "✅ Ask for specific information"] },
        { type: 'p', text: "**If someone asks for password:** It's a scam. Contact us immediately." },
      ] },
      { heading: "Troubleshooting", blocks: [
        { type: "h3", text: "Common Issues" },
        { type: 'p', text: "**Can't login:**" },
        { type: 'ul', items: ["Check email/password correct", "Try password reset", "Clear browser cache", "Try different browser", "Disable browser extensions", "Contact support"] },
        { type: 'p', text: "**2FA not working:**" },
        { type: 'ul', items: ["Check device time is correct", "Regenerate codes", "Try backup code", "Contact support"] },
        { type: 'p', text: "**Account settings not saving:**" },
        { type: 'ul', items: ["Check internet connection", "Refresh page", "Try different browser", "Contact support"] },
        { type: "h3", text: "Getting Help" },
        { type: 'p', text: "**Account or security questions?**" },
        { type: 'ul', items: ["**Email:** office@matjarx.com (most secure)", "**WhatsApp:** +92 303 372 0953", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "**Important:** Don't share password even with support. Ask for help instead." },
      ] },
      { heading: "Support", blocks: [
        { type: 'p', text: "**Need immediate help?**" },
        { type: 'ul', items: ["**WhatsApp:** +92 303 372 0953 (fastest)", "**Email:** office@matjarx.com", "**Phone:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11 AM - 8 PM PKT"] },
        { type: 'p', text: "[Contact Support →](#)" },
      ] },
    ],
    faqs: [
      ["How often should I change my password?", "Every 3-6 months is recommended. Immediately if compromised."],
      ["Is 2FA required?", "No, but highly recommended for security."],
      ["What if I lose my phone?", "Use backup codes to login. Disable 2FA and re-enable with new device."],
      ["Can I have multiple accounts?", "Yes. Manage separately or contact support to link."],
      ["What if I forget my 2FA backup codes?", "Contact support with proof of identity. We can help restore access."],
      ["Can you reset my password?", "You can reset yourself via email. If email hacked, contact support with ID proof."],
      ["Is my data backed up?", "Yes! Daily backups. Can be restored if needed."]
    ],
    related: [["Getting Started", "/help/getting-started/"], ["Billing & Plans", "/help/billing-and-plans/"], ["Privacy Policy", "/privacy-policy/"], ["Terms & Conditions", "/terms-and-conditions/"]],
  },
}
