// Data for the 3 Legal pages — from files/matjarx_terms_conditions.md,
// matjarx_refund_policy.md and matjarx_privacy_policy.md, generated from
// each document's own numbered-section/list/table structure. These
// supersede the earlier design-handoff paraphrase, whose refund/
// cancellation terms didn't match the real policy (see commit message).

export type LegalDoc = 'terms' | 'refund' | 'privacy'

export type LegalBlock =
  | { type: 'h3'; text: string }
  | { type: 'h4'; text: string }
  | { type: 'p'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }

export type LegalDocData = {
  label: string
  title: string
  updated: string
  intro: string
  sections: { heading: string; blocks: LegalBlock[] }[]
}

export const LEGAL_DATA: Record<LegalDoc, LegalDocData> = {
  terms: {
    label: "Terms & conditions",
    title: "MatjarX Terms and Conditions",
    updated: "January 1st, 2026",
    intro: "Welcome to MatjarX. These Terms and Conditions (\"Terms\") govern the use of services provided by MatjarX (\"Company\", \"we\", \"us\", or \"our\"). By purchasing, accessing, or using our services, you (\"Client\", \"you\", or \"your\") agree to comply with and be legally bound by these Terms. **If you do not agree with any part of these Terms, you must not use our services.**",
    sections: [
      { heading: "1. Company Information", blocks: [
        { type: 'ul', items: ["**Business Name:** MatjarX", "**Business Type:** Sole Proprietorship", "**Business Address:** B6, 4th Street, Zamzama, Clifton, Karachi, Pakistan", "**Support Email:** office@MatjarX.com", "**Phone / WhatsApp:** +92 303 3720953"] },
      ] },
      { heading: "2. Services Offered", blocks: [
        { type: 'p', text: "MatjarX provides digital services including but not limited to:" },
        { type: 'ul', items: ["WordPress website development", "Shopify store development", "Search Engine Optimization (SEO)", "Technical SEO and on-page optimization", "Local SEO services", "Social media management", "Website maintenance and support", "Hosting management and optimization", "Security monitoring and updates", "Plugin and theme updates", "Content edits and backup management", "Digital marketing services", "**Note:** All websites developed by MatjarX are primarily theme-based unless otherwise agreed in writing via a signed service agreement."] },
      ] },
      { heading: "3. Pricing and Plans", blocks: [
        { type: "h3", text: "Website Development Plans" },
        { type: "h4", text: "Launch Plan" },
        { type: 'ul', items: ["**One-Time Setup Fee:** PKR 22,500", "**Monthly Maintenance Fee:** PKR 4,500", "**Includes:** 5–10 pages, basic website, hosting, domain"] },
        { type: "h4", text: "Boost Plan" },
        { type: 'ul', items: ["**One-Time Setup Fee:** PKR 22,500", "**Monthly Maintenance Fee:** PKR 15,600", "**Includes:** 20–30 pages, advanced features, 1 blog post/month, VIP phone support, unlimited edits (first 30 days)"] },
        { type: "h4", text: "Growth Plan" },
        { type: 'ul', items: ["**One-Time Setup Fee:** PKR 22,500", "**Monthly Maintenance Fee:** PKR 27,000", "**Includes:** 50 pages, SEO services, 3 blog posts/month, dedicated marketing manager, 1-on-1 monthly growth meetings"] },
        { type: "h4", text: "Platinum Ecommerce Plan" },
        { type: 'ul', items: ["**One-Time Setup Fee:** PKR 140,000", "**Monthly Maintenance Fee:** PKR 55,000", "**Includes:** Unlimited pages, e-commerce management, advanced SEO, social media management, 10 blogs/month, 20 social media post designs, dedicated team", "**Additional Services:** Additional requirements outside the agreed scope may incur additional charges. Custom projects are priced individually."] },
      ] },
      { heading: "4. Payment Terms", blocks: [
        { type: 'p', text: "**Payment Method:** All payments are accepted via **bank transfer only**." },
        { type: 'p', text: "**Billing Details:**" },
        { type: 'ul', items: ["All prices are charged in Pakistani Rupees (PKR)", "Monthly subscriptions are billed in advance", "Monthly billing dates are based on the original signup date", "Clients receive invoices via email"] },
        { type: 'p', text: "**Payment Grace Period:**" },
        { type: 'ul', items: ["Clients are provided a **5-day grace period for overdue invoices**", "Failure to make payment within the grace period may result in service suspension"] },
      ] },
      { heading: "5. Refund Policy", blocks: [
        { type: "h3", text: "Setup Fees (One-Time Payments)" },
        { type: 'ul', items: ["Setup fees are **non-refundable once work has started**", "Refund requests may only be submitted **within 24 hours of payment** if the project has not significantly started", "If work has already begun (design, development, planning, or resource allocation), the setup fee becomes non-refundable"] },
        { type: "h3", text: "Custom Projects" },
        { type: 'p', text: "For custom or tailored projects:" },
        { type: 'ul', items: ["Refunds may be considered only if the client is dissatisfied", "MatjarX will deduct: operational costs, service fees, purchased assets (plugins, themes), third-party expenses", "Remaining eligible amount will be refunded within 30 days"] },
        { type: "h3", text: "Approved Work" },
        { type: 'ul', items: ["Any work approved verbally or in writing by the client becomes **non-refundable**", "This includes design approvals, content approvals, and feature implementations"] },
        { type: "h3", text: "Monthly Subscriptions" },
        { type: 'ul', items: ["Monthly subscription payments are **non-refundable once the billing cycle has started**", "Clients may cancel subscriptions with 30 days written notice"] },
        { type: "h3", text: "Non-Refundable Items" },
        { type: 'p', text: "The following are strictly non-refundable:" },
        { type: 'ul', items: ["Domain purchases", "Hosting fees (if purchased or managed by MatjarX)", "Third-party software or plugin costs", "Completed and approved milestones", "SEO work already performed", "Social media content already delivered or posted"] },
        { type: 'p', text: "**For detailed refund information, see our Refund Policy page.**" },
      ] },
      { heading: "6. Cancellation Policy", blocks: [
        { type: 'p', text: "**Cancellation Notice:** Clients may cancel services at any time by providing **at least 30 days written notice**." },
        { type: 'p', text: "**Upon Cancellation:**" },
        { type: 'ul', items: ["Monthly services will continue until the end of the active billing period", "Clients may request website files and migration assistance", "MatjarX is not responsible for third-party migration issues"] },
      ] },
      { heading: "7. Non-Payment and Suspension", blocks: [
        { type: 'p', text: "**In case of non-payment:**" },
        { type: 'ul', items: ["MatjarX will attempt to contact the client through calls, messages, emails, or meetings", "Services may be suspended after the grace period expires", "Websites and hosting services may be taken offline after 3 months of non-payment", "Website data may be permanently deleted after 1 year of inactivity or non-payment", "Restoration of suspended projects may require repayment of setup fees and maintenance costs", "After 1 year, projects may require complete redevelopment"] },
      ] },
      { heading: "8. Delivery Timelines", blocks: [
        { type: "h3", text: "Estimated Delivery Times" },
        { type: 'ul', items: ["**Launch Plan:** 7 business days", "**Boost Plan:** 7–14 business days", "**Growth Plan:** 7–14 business days", "**Platinum Plan:** 30–45 business days", "**Custom Projects:** Defined in signed service agreement"] },
        { type: "h3", text: "Reasons for Delays" },
        { type: 'p', text: "Delivery timelines may be extended due to:" },
        { type: 'ul', items: ["Delayed approvals from client", "Missing content or credentials", "Third-party service delays", "Platform restrictions or outages", "Client-requested changes or additions"] },
      ] },
      { heading: "9. Website Ownership", blocks: [
        { type: 'p', text: "**Ownership Rights:** Clients receive full ownership rights to their website **only after all invoices and dues are fully cleared**." },
        { type: 'p', text: "**Upon Completion and Full Payment:**" },
        { type: 'ul', items: ["WordPress admin access may be shared", "Shopify collaborator or admin access may be shared", "Hosting credentials and website files may be provided upon request", "Clients may migrate their website to another hosting provider"] },
        { type: 'p', text: "**Access Suspension:** MatjarX reserves the right to suspend access in cases of unpaid invoices or service violations." },
      ] },
      { heading: "10. SEO and Marketing Disclaimer", blocks: [
        { type: 'p', text: "**MatjarX does not guarantee:**" },
        { type: 'ul', items: ["Specific Google rankings", "Website traffic volume", "Sales or revenue", "Lead generation numbers", "Revenue growth", "**Important Note:** SEO and digital marketing results depend on multiple external factors including:", "Market competition", "Search engine algorithm changes", "Market conditions", "Client participation and implementation", "Industry trends"] },
        { type: 'p', text: "While we apply industry best practices and optimization strategies, all results are estimates and cannot be guaranteed." },
        { type: 'ul', items: ["**AI-Assisted Content:** MatjarX may use hybrid AI-assisted and human-generated content creation methods. All content is reviewed and managed as part of our service workflows."] },
      ] },
      { heading: "11. Support Policy", blocks: [
        { type: "h3", text: "Support Hours" },
        { type: 'p', text: "**Monday to Saturday** **11:00 AM – 8:00 PM Pakistan Standard Time (PKT)**" },
        { type: 'p', text: "Closed: Sunday and public holidays" },
        { type: "h3", text: "Support Channels" },
        { type: 'ul', items: ["**WhatsApp:** Sales and general support", "**Email:** Billing, refunds, contracts, and documentation", "**Phone Support:** VIP and Platinum clients (priority)", "**Live Chat:** Website support"] },
        { type: "h3", text: "Response Time" },
        { type: 'ul', items: ["**Average response time:** Within 24 business hours", "**WhatsApp/Chat:** Usually 2-4 hours during business hours", "**Email:** Within 24 business hours"] },
        { type: "h3", text: "Emergency Support" },
        { type: 'p', text: "Emergency support for the following issues is prioritized for VIP and Platinum clients:" },
        { type: 'ul', items: ["Website downtime", "Security breaches or malware", "Critical website functionality errors", "Data loss"] },
      ] },
      { heading: "12. Client Responsibilities", blocks: [
        { type: 'p', text: "Clients are responsible for:" },
        { type: 'ul', items: ["Providing accurate information", "Sharing required access credentials and credentials", "Reviewing and approving work on time", "Maintaining lawful website content", "Ensuring they own rights to submitted materials (photos, content, etc.)", "Updating passwords after project completion", "**Note:** Delays caused by missing approvals or incomplete submissions may affect project timelines."] },
      ] },
      { heading: "13. Third-Party Services", blocks: [
        { type: 'p', text: "MatjarX may integrate or work with third-party services including:" },
        { type: 'ul', items: ["Shopify", "WordPress plugins and themes", "Hosting providers", "Google services", "Meta platforms", "Payment gateways", "SEO tools", "Email service providers", "**Disclaimer:** We are not liable for:", "Outages or service interruptions", "Policy changes by third parties", "Pricing changes", "Account suspensions", "Service failures caused by third-party providers"] },
      ] },
      { heading: "14. Intellectual Property", blocks: [
        { type: 'p', text: "**Custom Work:** All custom work created by MatjarX remains the property of MatjarX until full payment is received." },
        { type: 'p', text: "**Client Ownership:** Clients retain ownership of their logos, trademarks, and original content." },
        { type: 'p', text: "**Portfolio Rights:** MatjarX reserves the right to display completed projects in portfolios and marketing materials unless otherwise agreed in writing." },
      ] },
      { heading: "15. Limitation of Liability", blocks: [
        { type: 'p', text: "MatjarX shall not be liable for:" },
        { type: 'ul', items: ["Indirect or consequential losses", "Loss of profits or revenue", "Data loss caused by third-party providers", "Search engine ranking fluctuations", "Cybersecurity incidents beyond reasonable control", "Delays caused by external services"] },
        { type: 'p', text: "**Cap on Liability:** Our total liability shall not exceed the total amount paid by the client for the affected service." },
      ] },
      { heading: "16. Termination of Services", blocks: [
        { type: 'p', text: "MatjarX reserves the right to terminate services if:" },
        { type: 'ul', items: ["The client violates these Terms", "Payments remain unpaid (after grace period and notices)", "The client engages in abusive, illegal, or fraudulent activity", "The website content violates applicable laws", "The client misuses the service"] },
      ] },
      { heading: "17. Governing Law and Jurisdiction", blocks: [
        { type: 'p', text: "**Governing Law:** These Terms shall be governed and interpreted in accordance with the **laws of Pakistan**." },
        { type: 'p', text: "**Jurisdiction:** Any disputes arising from these Terms shall fall under the jurisdiction of the **courts of Karachi, Pakistan**." },
      ] },
      { heading: "18. Changes to Terms", blocks: [
        { type: 'p', text: "MatjarX reserves the right to update or modify these Terms at any time without prior notice." },
        { type: 'p', text: "**Effect of Changes:** Continued use of services after updates constitutes acceptance of the revised Terms." },
      ] },
      { heading: "19. Contact Information", blocks: [
        { type: 'p', text: "**For legal, billing, or support inquiries:**" },
        { type: 'p', text: "**MatjarX** B6, 4th Street, Zamzama, Clifton Karachi, Pakistan" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Phone / WhatsApp:** +92 303 3720953", "**Effective Date:** January 1st, 2026"] },
      ] },
      { heading: "Summary", blocks: [
        { type: 'p', text: "**By using MatjarX services, you agree to:**" },
        { type: 'ul', items: ["Pay as outlined in the pricing section", "Follow the cancellation and refund policies", "Take responsibility for content and credentials", "Understand that SEO results cannot be guaranteed", "Accept our limitation of liability", "Resolve disputes under Pakistani law"] },
        { type: 'p', text: "**Questions about these Terms?** Contact us at office@MatjarX.com or WhatsApp +92 303 372 0953" },
      ] },
    ],
  },
  refund: {
    label: "Refund policy",
    title: "MatjarX Refund Policy",
    updated: "January 1st, 2026",
    intro: "This Refund Policy applies to all services provided by MatjarX (\"Company\", \"we\", \"us\", or \"our\"), operated as a sole proprietorship based in Karachi, Pakistan. **By purchasing any service from MatjarX, you agree to the refund terms outlined below.**",
    sections: [
      { heading: "1. General Policy Overview", blocks: [
        { type: 'p', text: "MatjarX provides digital services including website development, SEO, maintenance, and marketing services. Due to the nature of digital work, resource allocation, and time investment, our refund policy is structured to ensure fairness for both clients and the company." },
        { type: 'ul', items: ["**Important:** Refunds are not guaranteed and are only issued under specific conditions outlined in this policy."] },
      ] },
      { heading: "2. Setup Fees (One-Time Payments)", blocks: [
        { type: "h3", text: "Non-Refundable Once Work Begins" },
        { type: 'p', text: "**Setup fees are non-refundable once work has started.**" },
        { type: 'ul', items: ["**Development:** Design, development, planning, or resource allocation has begun", "**Content Creation:** Copywriting, research, or content drafting has started", "**Configuration:** Website setup, theme selection, or plugin installation has started", "**Testing:** Quality assurance or testing processes have commenced"] },
        { type: "h3", text: "24-Hour Refund Window" },
        { type: 'p', text: "Clients may request a refund **within 24 hours of payment** if:" },
        { type: 'ul', items: ["✅ The project has not significantly started", "✅ No resources have been allocated to the project", "✅ No design or development work has commenced"] },
        { type: 'p', text: "**After 24 hours or once work begins, the setup fee becomes non-refundable.**" },
        { type: "h3", text: "How to Request a 24-Hour Refund" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Subject:** \"Refund Request - [Your Project Name]\""] },
        { type: 'p', text: "Include:" },
        { type: 'ul', items: ["Invoice number", "Date of payment", "Reason for refund request", "**Response Time:** Within 24 business hours"] },
      ] },
      { heading: "3. Custom Projects Refunds", blocks: [
        { type: "h3", text: "Partial Refunds Available Only Under Specific Conditions" },
        { type: 'p', text: "For custom or tailored projects, refunds may be considered only if:" },
        { type: 'ul', items: ["Client is dissatisfied with delivered work", "The work does not meet documented specifications", "Work approval has not been granted"] },
        { type: "h3", text: "Deductions from Refund Amount" },
        { type: 'p', text: "If a refund is approved, MatjarX will deduct:" },
        { type: 'p', text: "**Service and Operational Costs:**" },
        { type: 'ul', items: ["Project management time", "Team coordination", "Administrative processing"] },
        { type: 'p', text: "**Time Invested:**" },
        { type: 'ul', items: ["Hours spent on design, development, and implementation", "Research and planning", "Revisions and adjustments", "Communication and meetings"] },
        { type: 'p', text: "**Purchased Assets:**" },
        { type: 'ul', items: ["WordPress plugins or themes", "Shopify apps or premium features", "Third-party tools or software", "Stock photos or resources", "Hosting or domain fees", "API integrations or services"] },
        { type: 'p', text: "**Remaining Eligible Amount:** After all deductions, any remaining balance (if applicable) will be refunded." },
        { type: "h3", text: "Refund Processing Timeline" },
        { type: 'p', text: "Approved refunds are processed within **30 business days**." },
        { type: 'ul', items: ["**Refund Method:** Bank transfer only", "**Notification:** You will receive detailed breakdown of deductions via email before processing"] },
        { type: "h3", text: "Project Files Upon Refund" },
        { type: 'p', text: "Upon approval of refund, MatjarX may deliver:" },
        { type: 'ul', items: ["Website files in their current completed state", "Database backups (if applicable)", "Documentation of work completed", "Access credentials and setup details"] },
      ] },
      { heading: "4. Approved Work Policy", blocks: [
        { type: "h3", text: "Final and Non-Refundable" },
        { type: 'p', text: "**Any work that has been approved—verbally or in writing—is final and non-refundable under all circumstances.**" },
        { type: 'p', text: "**Approval includes:**" },
        { type: 'ul', items: ["Verbal approval (phone call, WhatsApp conversation)", "Written approval (email, message confirmation)", "Signed approval on project documentation", "Published content on your website", "Implemented features or functionality"] },
        { type: 'p', text: "**Once approved, you cannot request a refund for that specific work.**" },
        { type: "h3", text: "Example Scenarios" },
        { type: 'ul', items: ["**Scenario 1:** You approve website design via email. Later, you want different colors.", "**Result:** Not refundable (already approved)", "**Scenario 2:** You approve a blog post in a WhatsApp conversation. Later, you want it rewritten.", "**Result:** Not refundable (already approved). Revision would be a new service.", "**Scenario 3:** A feature is implemented and you test it. You ask for changes and approve the revised version.", "**Result:** Not refundable (approved in its final form)"] },
      ] },
      { heading: "5. Monthly Subscription Services", blocks: [
        { type: "h3", text: "Non-Refundable After Billing Cycle Starts" },
        { type: 'p', text: "**All monthly plan payments are non-refundable once the billing cycle has started.**" },
        { type: "h3", text: "Included Non-Refundable Services" },
        { type: 'p', text: "The following are included in monthly plans and are non-refundable:" },
        { type: 'ul', items: ["Website maintenance plans", "SEO services", "Social media management", "Content creation and blog posts", "Hosting and support services", "Platform updates and monitoring", "Backup and security services"] },
        { type: "h3", text: "Subscription Cancellation" },
        { type: 'p', text: "**Clients may cancel subscriptions anytime, but:**" },
        { type: 'ul', items: ["A **30-day written notice is required**", "Services remain active through the end of the notice period", "No refunds issued for remaining billing cycle duration"] },
        { type: "h3", text: "Cancellation Process" },
        { type: 'p', text: "**To cancel your subscription:**" },
        { type: 'ul', items: ["**Send email to:** office@MatjarX.com", "**Subject:** \"Subscription Cancellation Request\""] },
        { type: 'p', text: "Include:" },
        { type: 'ul', items: ["Your name", "Website URL or project name", "Current plan name", "Requested cancellation date", "Reason for cancellation (optional)", "**Confirmation:** You will receive cancellation confirmation within 24 business hours"] },
      ] },
      { heading: "6. Non-Refundable Services", blocks: [
        { type: "h3", text: "Strictly Non-Refundable" },
        { type: 'p', text: "The following services and expenses are **strictly non-refundable**:" },
        { type: 'p', text: "**Domain Purchases**" },
        { type: 'ul', items: ["Domain registration fees", "Domain renewal fees", "Domain transfer fees"] },
        { type: 'p', text: "**Hosting Fees**" },
        { type: 'ul', items: ["Monthly hosting charges", "Hosting setup fees", "Hosting renewal fees", "If purchased or managed on behalf of client"] },
        { type: 'p', text: "**Third-Party Services**" },
        { type: 'ul', items: ["Plugin purchases or licenses", "Theme purchases or licenses", "Software or tool subscriptions", "Stock photo or media purchases", "API service subscriptions", "Third-party integrations and add-ons"] },
        { type: 'p', text: "**Completed and Approved Work**" },
        { type: 'ul', items: ["Design and development work (once approved)", "Content and copywriting (once approved)", "SEO work already performed", "Social media posts already created and delivered", "Features and functionality implemented"] },
        { type: 'p', text: "**SEO and Marketing Services**" },
        { type: 'ul', items: ["SEO services already performed", "Content optimization work", "Keyword research and strategy", "Backlink work and citations", "Page speed optimization", "Technical SEO improvements"] },
        { type: 'p', text: "**Social Media Content**" },
        { type: 'ul', items: ["Social media posts already delivered", "Social media content already posted", "Content calendar creation", "Social media strategy work"] },
      ] },
      { heading: "7. Cancellation and Refund Eligibility", blocks: [
        { type: "h3", text: "How to Cancel Services" },
        { type: 'p', text: "**Clients may cancel services at any time, but must provide:**" },
        { type: 'ul', items: ["**30-day written notice** (via email to office@MatjarX.com)", "Services remain active during the 30-day notice period", "No refund for remaining portion of active billing cycle"] },
        { type: "h3", text: "Cancellation Benefits" },
        { type: 'p', text: "Upon cancellation, MatjarX will assist with:" },
        { type: 'ul', items: ["**Project Files:** Delivery of website files in their current state", "**Migration Support:** Guidance for moving to another provider", "**Access Transfer:** Instructions for updating passwords and access", "**Documentation:** Provision of technical documentation"] },
        { type: "h3", text: "Data After Cancellation" },
        { type: 'ul', items: ["**Note:** Data may be deleted after 1 year of inactivity or non-payment. For data preservation, arrange transfer or download before cancellation period ends."] },
      ] },
      { heading: "8. Project Suspension and Non-Payment", blocks: [
        { type: "h3", text: "Payment Reminders" },
        { type: 'p', text: "If a client fails to make payment, MatjarX will attempt contact through:" },
        { type: 'ul', items: ["WhatsApp messages", "Email notifications", "Phone calls", "Direct meetings"] },
        { type: "h3", text: "Grace Period" },
        { type: 'p', text: "A grace period is provided before service suspension (typically 5 days, though specific periods may be defined in your service agreement)." },
        { type: "h3", text: "Service Suspension" },
        { type: 'p', text: "**After grace period expires, services may be suspended:**" },
        { type: 'ul', items: ["Website access may be restricted", "Email services may be suspended", "Support services may be halted", "Platform access may be limited"] },
        { type: "h3", text: "Website Offline Status" },
        { type: 'p', text: "**After 3 months of non-payment:**" },
        { type: 'ul', items: ["Your website may be taken offline", "Website files may be stored but not publicly accessible", "Hosting and domain services may be suspended"] },
        { type: "h3", text: "Data Deletion Policy" },
        { type: 'p', text: "**After 1 year of inactivity or non-payment:**" },
        { type: 'ul', items: ["Website data may be permanently deleted", "Database backups may be removed", "Website files may be permanently removed", "Data recovery may not be possible"] },
        { type: "h3", text: "Reactivation After Suspension" },
        { type: 'p', text: "To restore suspended projects, clients may be required to:" },
        { type: 'ul', items: ["**Pay all outstanding invoices** (principal amount)", "**Pay reactivation fees** (if applicable)", "**Pay updated service charges** (for storage or restoration)", "**Warning:** After 1 year of suspension, a project may require complete redevelopment rather than simple reactivation. Redevelopment costs may apply."] },
      ] },
      { heading: "9. Refund Processing Timeline", blocks: [
        { type: "h3", text: "If Refund is Approved" },
        { type: 'ul', items: ["**Processing timeline:** Up to **30 business days**"] },
        { type: "h3", text: "Bank Transfer Only" },
        { type: 'p', text: "All refunds are issued via **bank transfer only**." },
        { type: 'ul', items: ["Refunds are not issued as credits or store vouchers", "Bank transfer is to the account provided at time of purchase", "Allow additional 3-5 business days for bank processing"] },
        { type: "h3", text: "Communication Before Processing" },
        { type: 'p', text: "Before processing a refund, MatjarX will:" },
        { type: 'ul', items: ["Send detailed breakdown of deductions via email", "Explain the calculation and reasoning", "Provide documentation of costs incurred", "Allow time for client questions or clarifications"] },
      ] },
      { heading: "10. Dispute Resolution", blocks: [
        { type: "h3", text: "How to Handle Disputes" },
        { type: 'p', text: "**In case of disputes:**" },
        { type: 'p', text: "**Step 1: Direct Communication**" },
        { type: 'ul', items: ["Contact MatjarX at office@MatjarX.com", "Provide detailed explanation of the dispute", "Allow 48 hours for response"] },
        { type: 'p', text: "**Step 2: Discussion and Resolution**" },
        { type: 'ul', items: ["MatjarX will review the dispute", "We aim to resolve through communication, revisions, or adjustments", "Alternative solutions may be offered"] },
        { type: 'p', text: "**Step 3: Formal Dispute Process**" },
        { type: 'ul', items: ["If unresolved, provide formal written complaint", "Include all supporting documentation", "Allow up to 2 weeks for review"] },
        { type: 'p', text: "**Step 4: Legal Jurisdiction**" },
        { type: 'ul', items: ["If still unresolved, legal jurisdiction falls under **Karachi, Pakistan**", "Disputes will be handled according to **Pakistani law**"] },
        { type: "h3", text: "Contact for Disputes" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Subject:** \"Refund Dispute - [Your Project Name]\""] },
        { type: 'p', text: "Include:" },
        { type: 'ul', items: ["Invoice number and project details", "Detailed explanation of dispute", "Supporting documentation (emails, messages, approvals, etc.)", "Screenshots or evidence if applicable"] },
      ] },
      { heading: "11. Special Circumstances", blocks: [
        { type: "h3", text: "Circumstances NOT Covered by Refund Policy" },
        { type: 'p', text: "Refunds are not provided for:" },
        { type: 'ul', items: ["Change of mind after approval", "Budget constraints or financial hardship", "Business closure or circumstances", "Project no longer needed", "Preference for alternative solution", "Dissatisfaction with marketing results (SEO/marketing can't be guaranteed)"] },
        { type: "h3", text: "Refund Exceptions" },
        { type: 'p', text: "MatjarX may consider refund exceptions only in cases of:" },
        { type: 'ul', items: ["**Service Failure:** Significant failure to deliver contracted services", "**Data Loss:** Loss of data through MatjarX negligence", "**Security Breach:** Security incident caused by MatjarX", "**Extended Delays:** Delays significantly beyond stated timelines without client cause"] },
        { type: 'p', text: "**Exceptions are reviewed on a case-by-case basis.**" },
      ] },
      { heading: "12. Refund Request Form", blocks: [
        { type: "h3", text: "How to Request a Refund" },
        { type: 'p', text: "**Step 1: Gather Information**" },
        { type: 'ul', items: ["Invoice number", "Date of payment", "Amount paid", "Reason for refund request", "Project name or website URL"] },
        { type: 'p', text: "**Step 2: Send Email Request**" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Subject:** \"Refund Request - [Project Name]\""] },
        { type: 'p', text: "**Step 3: Provide Details** Include in your email:" },
        { type: 'ul', items: ["Your full name and contact information", "Invoice number", "Date and amount of payment", "Clear explanation of reason for refund", "Any supporting documentation (screenshots, emails, etc.)"] },
        { type: 'p', text: "**Step 4: Response**" },
        { type: 'ul', items: ["MatjarX will review within 24-48 business hours", "You'll receive a response via email", "If approved, processing begins within 30 days"] },
      ] },
      { heading: "13. Contact Information", blocks: [
        { type: "h3", text: "For Refund-Related Inquiries" },
        { type: 'p', text: "**MatjarX** B6, 4th Street, Zamzama, Clifton Karachi, Sindh, Pakistan" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Phone / WhatsApp:** +92 303 372 0953", "**Hours:** Monday-Saturday, 11:00 AM – 8:00 PM PKT"] },
        { type: "h3", text: "Response Times" },
        { type: 'ul', items: ["**Email inquiries:** 24 business hours", "**WhatsApp inquiries:** 2-4 hours (business hours)", "**Phone:** Available during business hours"] },
      ] },
      { heading: "14. Summary of Key Points", blocks: [
        { type: "h3", text: "Quick Reference" },
        { type: 'table', headers: ["Situation", "Refundable?", "Timeline", "Notes"], rows: [["Setup fee (within 24 hrs, no work started)", "✅ Yes", "30 days", "Request within 24 hours"], ["Setup fee (after work starts)", "❌ No", "—", "Non-refundable"], ["Approved work", "❌ No", "—", "Final once approved"], ["Monthly subscription (during cycle)", "❌ No", "—", "Cancel with 30 days notice"], ["Domain purchase", "❌ No", "—", "Non-refundable"], ["Third-party services", "❌ No", "—", "Non-refundable"], ["Custom project (dissatisfied)", "⚠️ Partial", "30 days", "Deductions apply"], ["Non-payment suspension", "✅ Reactivation", "—", "May require reactivation fees"]] },
      ] },
      { heading: "15. Effective Date and Updates", blocks: [
        { type: 'ul', items: ["**Effective Date:** January 1st, 2026"] },
        { type: 'p', text: "MatjarX reserves the right to update this Refund Policy at any time. Changes will be posted on our website, and continued use of services constitutes acceptance of updated policy terms." },
      ] },
      { heading: "Important Reminders", blocks: [
        { type: 'ul', items: ["✅ **Read Before Purchasing:** Understand these terms before making any payment", "✅ **Keep Records:** Save all invoices and communication for reference", "✅ **Get Approval:** Ensure any work is approved before considering it final", "✅ **Request Early:** Submit refund requests within specified timeframes", "✅ **Provide Details:** Include all necessary information in refund requests", "✅ **Follow Process:** Use official channels and procedures for requests"] },
        { type: 'p', text: "**Questions about this policy?**" },
        { type: 'p', text: "Contact MatjarX at office@MatjarX.com or +92 303 372 0953" },
        { type: 'ul', items: ["**Last Updated:** January 1st, 2026"] },
      ] },
    ],
  },
  privacy: {
    label: "Privacy & cookies",
    title: "MatjarX Privacy Policy",
    updated: "January 1st, 2026",
    intro: "MatjarX (\"Company\", \"we\", \"us\", or \"our\") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, store, and protect information when you use our website, services, or communicate with us. **By using our website or services, you agree to the collection and use of information in accordance with this Privacy Policy.**",
    sections: [
      { heading: "1. Company Information", blocks: [
        { type: 'ul', items: ["**Business Name:** MatjarX", "**Business Type:** Sole Proprietorship", "**Business Address:** B6, 4th Street, Zamzama, Clifton, Karachi, Pakistan", "**Support Email:** office@MatjarX.com", "**Phone / WhatsApp:** +92 303 3720953"] },
      ] },
      { heading: "2. Information We Collect", blocks: [
        { type: "h3", text: "Personal Information" },
        { type: 'p', text: "We may collect the following types of personal information when you use our services:" },
        { type: 'ul', items: ["Full name", "Email address", "Phone number", "Business information", "Website URLs", "Project details and requirements", "Billing and payment information"] },
        { type: "h3", text: "Technical and Website Data" },
        { type: 'p', text: "We may receive access to or collect data related to:" },
        { type: 'ul', items: ["WordPress websites", "Shopify stores", "Google Analytics data", "Google Search Console data", "Meta Pixel information", "Bing Webmaster Tools data", "Google Business Profile information", "Website performance analytics", "Website usage statistics"] },
        { type: "h3", text: "Communication Information" },
        { type: 'p', text: "When you contact us through:" },
        { type: 'ul', items: ["Website contact forms", "Email", "WhatsApp", "Phone calls", "Social media platforms"] },
        { type: 'p', text: "We may store communication records for support, billing, legal, and operational purposes." },
      ] },
      { heading: "3. How We Use Your Information", blocks: [
        { type: 'p', text: "We use collected information for the following purposes:" },
        { type: 'ul', items: ["**Service Delivery:** Providing website development, SEO, and digital marketing services", "**Project Management:** Managing your website projects and requirements", "**Customer Support:** Responding to inquiries and providing technical support", "**Billing & Payments:** Processing invoices, payments, and financial records", "**Performance Improvement:** Improving website performance and service quality", "**Maintenance & Security:** Managing website maintenance, security, and updates", "**Analytics & Reporting:** Creating performance reports and analytics", "**Legal Compliance:** Responding to legal obligations and regulatory requirements", "**Fraud Prevention:** Detecting and preventing fraud or misuse of services"] },
      ] },
      { heading: "4. Analytics and Tracking Tools", blocks: [
        { type: 'p', text: "MatjarX may use third-party analytics and marketing tools including:" },
        { type: 'ul', items: ["Google Analytics", "Google Search Console", "Meta Pixel", "Bing Webmaster Tools", "Shopify analytics tools", "WordPress plugins and analytics systems"] },
        { type: 'p', text: "**These tools may collect:**" },
        { type: 'ul', items: ["IP addresses", "Device information", "Browser type", "Website usage behavior", "Traffic and interaction data"] },
        { type: 'p', text: "**We use these tools solely to:**" },
        { type: 'ul', items: ["Improve performance", "Enhance marketing effectiveness", "Provide better analytics", "Improve customer experience"] },
      ] },
      { heading: "5. Payment Information", blocks: [
        { type: 'p', text: "**MatjarX accepts payments through bank transfer only.**" },
        { type: 'p', text: "**We do not directly collect or store:**" },
        { type: 'ul', items: ["Credit card information", "Debit card information", "Banking passwords", "Financial authentication credentials"] },
        { type: 'p', text: "**Clients are responsible for securely processing payments through their banking provider.**" },
      ] },
      { heading: "6. Third-Party Services", blocks: [
        { type: 'p', text: "We may use or integrate with third-party platforms including:" },
        { type: 'ul', items: ["Shopify", "WordPress", "Hosting providers", "Google services", "Meta platforms", "Social media platforms", "SEO tools", "Email service providers", "**Important:** These third-party services may independently collect or process user data according to their own privacy policies. MatjarX is not responsible for the privacy practices of third-party platforms."] },
      ] },
      { heading: "7. Data Sharing", blocks: [
        { type: 'p', text: "**MatjarX does not sell personal information.**" },
        { type: 'p', text: "We may share information only when necessary for:" },
        { type: 'ul', items: ["Providing requested services", "Technical integrations", "Legal compliance", "Website hosting and maintenance", "SEO and marketing operations", "Protecting our legal rights"] },
        { type: 'p', text: "**Information may be shared with trusted service providers or contractors only when required for project delivery.**" },
      ] },
      { heading: "8. Data Retention", blocks: [
        { type: 'ul', items: ["We retain client information for operational, legal, accounting, and support purposes", "Inactive or unpaid project data may be deleted after one year of inactivity or non-payment", "Communication records, invoices, and agreements may be retained for legal and business documentation purposes", "Upon client request and full payment settlement, we can assist with data retrieval and transfer"] },
      ] },
      { heading: "9. Data Security", blocks: [
        { type: 'p', text: "We implement reasonable security measures to protect client information and website access:" },
        { type: 'ul', items: ["Secure password handling and encryption", "Access controls and user authentication", "Regular backup systems", "Malware monitoring and protection", "Security plugins and hosting protections", "SSL certificates for all websites", "Regular security updates", "**Important Disclaimer:** No online system is completely secure. While we implement industry-standard security practices, MatjarX cannot guarantee absolute security of digital information. Clients are responsible for maintaining strong passwords and updating credentials after project completion."] },
      ] },
      { heading: "10. Website Access and Credentials", blocks: [
        { type: 'p', text: "Clients may provide the following for project completion:" },
        { type: 'ul', items: ["Website credentials (WordPress, Shopify, etc.)", "Hosting access", "Analytics access", "Business platform permissions", "API keys or integration credentials"] },
        { type: 'p', text: "**MatjarX agrees to use such access only for authorized business purposes related to your project.**" },
        { type: 'p', text: "**Client Responsibilities:**" },
        { type: 'ul', items: ["Maintain ownership of their accounts", "Update passwords after project completion if desired", "Review granted permissions periodically", "Notify us of any unauthorized access"] },
      ] },
      { heading: "11. AI-Assisted Content", blocks: [
        { type: 'p', text: "MatjarX may use hybrid AI-assisted and human-created content generation methods for:" },
        { type: 'ul', items: ["SEO content creation", "Blog writing", "Social media content", "Website copywriting", "Optimization recommendations"] },
        { type: 'p', text: "**All content is reviewed and managed as part of our service workflows to ensure quality and accuracy.**" },
      ] },
      { heading: "12. Client Rights", blocks: [
        { type: 'p', text: "Clients may request:" },
        { type: 'ul', items: ["Access to their information", "Correction of inaccurate information", "Deletion of certain information where legally permitted", "Removal of website access permissions"] },
        { type: 'p', text: "**Requests may be submitted via email at office@MatjarX.com**" },
      ] },
      { heading: "13. International Data Usage", blocks: [
        { type: 'p', text: "Although MatjarX operates in Pakistan, some third-party services used by us may process data internationally." },
        { type: 'p', text: "**By using our services, you acknowledge that certain information may be processed outside Pakistan through third-party platforms including:**" },
        { type: 'ul', items: ["Google (United States)", "Meta (United States)", "Shopify (Canada/United States)", "Hosting providers (various locations)"] },
      ] },
      { heading: "14. Children's Privacy", blocks: [
        { type: 'p', text: "**MatjarX services are not intended for individuals under the age of 18.**" },
        { type: 'p', text: "We do not knowingly collect personal information from minors. If we become aware that a minor has provided personal information, we will delete such information promptly." },
      ] },
      { heading: "15. Changes to This Privacy Policy", blocks: [
        { type: 'p', text: "MatjarX reserves the right to update or modify this Privacy Policy at any time." },
        { type: 'ul', items: ["Changes become effective immediately upon publication on our website", "We will notify clients of major changes via email when possible", "Continued use of our services constitutes acceptance of updated policies"] },
      ] },
      { heading: "16. Contact Information", blocks: [
        { type: 'p', text: "**For privacy-related inquiries or requests:**" },
        { type: 'p', text: "**MatjarX** B6, 4th Street, Zamzama, Clifton Karachi, Pakistan" },
        { type: 'ul', items: ["**Email:** office@MatjarX.com", "**Phone / WhatsApp:** +92 303 3720953"] },
        { type: 'p', text: "**Date: January 1st, 2026**" },
      ] },
      { heading: "Summary: Your Privacy at MatjarX", blocks: [
        { type: 'ul', items: ["**We Collect:** Information necessary to provide services (personal data, website data, analytics)", "**We Use:** This information solely to improve our service and help your business", "**We Protect:** Your data with industry-standard security measures", "**We Share:** Only with trusted partners necessary for service delivery", "**We Never Sell:** Your personal information to third parties", "**You Control:** Your data and can request access, correction, or deletion anytime"] },
      ] },
    ],
  },
}

export const LEGAL_DOC_KEYS: LegalDoc[] = ['terms', 'refund', 'privacy']
