// Full-fidelity 'process' / 'plans' / 'whyOver' content for all 63 city
// pages, extracted from files/matjarx_website_design_*.md — verbatim.
// location-data.ts (CITY_DATA) already carries real why/industries/faqs
// content for every city; this file adds the 3 sections no city page had
// at all: the 3-step build process, the 4-tier plan breakdown, and the
// "MatjarX vs other options" comparison — present in every source file,
// terse for smaller cities and detailed for larger ones, exactly as written.

import type { CityKey } from './location-data'

export type CityProcessStep = { title: string; body: string }
export type CityPlanTier = { name: string; price: string; setup: string; items: string[] }
export type CityCompareGroup = { label: string; items: string[] }

export const CITY_DETAIL: Record<CityKey, { process: CityProcessStep[]; plans: CityPlanTier[]; whyOver: CityCompareGroup[] }> = {
  'abbottabad': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'attock': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'bahawalnagar': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, you own it.'] }, { label: 'Platforms', items: ['Local support, no hidden costs.'] }, { label: 'WordPress', items: ['Fully managed, simple.'] }],
  },
  'bahawalpur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs, builds, and optimizes. SEO setup. Payment integration. All technical work handled.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. Google submission. Within 4 weeks, you\'re ranking for your keywords.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited, e-commerce, 10 blogs, 20 social posts, full team)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'vs. Platforms', items: ['Local, supported, transparent.'] }, { label: 'vs. WordPress', items: ['Managed, simple, affordable.'] }],
  },
  'burewala': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, you own it.'] }, { label: 'Platforms', items: ['Local support, no hidden costs.'] }, { label: 'WordPress', items: ['Fully managed, simple.'] }],
  },
  'charsadda': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'chichawatni': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'chiniot': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates. All technical.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'dadu': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'daska': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'dera-ghazi-khan': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates. All technical work.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking for keywords.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs/month, 20 social posts, ads)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['7 days, PKR 22,500, yours to keep.'] }, { label: 'vs. Global Platforms', items: ['Local support, local payments, transparent.'] }, { label: 'vs. WordPress', items: ['Fully managed, no complexity.'] }],
  },
  'dera-ismail-khan': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'faisalabad': {
    process: [{ title: 'Discovery (Day 1)', body: '30-minute consultation about your business. What you sell, who your customers are, what success means to you.' }, { title: 'Build (Days 2-7)', body: 'Our team designs, builds, and optimizes. SEO configuration. Local payment setup. Blog templates. Email configuration. Social media preparation. You provide direction; we do the work.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google Search Console. Within 4 weeks, you\'re ranking for your keywords. Organic customers start flowing in.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Core website features', 'Hosting + domain included', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'Advanced SEO optimization', '1 blog post/month', 'Priority support', 'Unlimited email accounts'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blog posts/month', 'Dedicated growth expert', 'Monthly 1-on-1 strategy call', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000 (for complex projects)', items: ['Unlimited pages/products', 'Full e-commerce platform', '10 blog posts/month', '20 social media posts/month', 'Managed advertising campaigns', 'Complete team support'] }],
    whyOver: [{ label: 'vs. Faisalabad Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes included.', 'Agencies: You depend on them. Us: You own your website.', 'Result: Faster, cheaper, complete independence.'] }, { label: 'vs. Global Platforms (Wix, Squarespace)', items: ['No local payment methods (Wix, Squarespace).', 'No Pakistan-based support team.', 'No included marketing or growth strategy.', 'Hidden app costs add up over time.', 'Result: Higher actual costs, slower results.'] }, { label: 'vs. Self-Managed WordPress', items: ['WordPress: Complex maintenance burden (plugins, updates, security).', 'Us: Fully managed, automated, zero technical knowledge needed.', 'WordPress: Hidden costs—hosting, plugins, tools = PKR 15,000–25,000/month.', 'Us: One transparent fee includes everything.', 'Result: Simpler, cheaper, faster results.'] }],
  },
  'gojra': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'gujranwala': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We understand your goals and growth vision.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media preparation. All technical work handled.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Customers find you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting + domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs/month, 20 social posts)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Gujranwala Agencies', items: ['Faster (7 days vs 4–8 weeks), cheaper (PKR 22,500 vs PKR 300,000+), yours to keep.'] }, { label: 'vs. Global Platforms', items: ['No local payments, no local support, hidden costs.'] }, { label: 'vs. WordPress DIY', items: ['Complex, PKR 15,000–25,000/month hidden costs, maintenance burden.'] }],
  },
  'gujrat': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, 1 blog)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs, expert)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited, e-commerce, 10 blogs, full team)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['7 days, PKR 22,500, complete ownership.'] }, { label: 'vs. Global platforms', items: ['Local support, local payments, no hidden costs.'] }, { label: 'vs. WordPress', items: ['Fully managed, no complexity, affordable.'] }],
  },
  'hafizabad': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'haripur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'hyderabad': {
    process: [{ title: 'Discovery (Day 1)', body: '— Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: '— Our team designs and builds. SEO setup. Payment integration. Templates. All technical work.' }, { title: 'Launch (Day 7+)', body: '— Your website goes live. Submit to Google. Within 4 weeks, ranking for your keywords.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, 1 blog/month)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited, e-commerce, 10 blogs, full team)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['7 days vs weeks, PKR 22,500 vs PKR 300,000+.'] }, { label: 'vs. Platforms', items: ['Local payments, local support, no hidden costs.'] }, { label: 'vs. WordPress', items: ['Managed, no complexity, no hidden costs.'] }],
  },
  'islamabad': {
    process: [{ title: 'Discovery (Day 1)', body: '30-minute call about your business. What do you sell? Who are your customers? What are your goals?' }, { title: 'Build (Days 2-7)', body: 'Our team designs, builds, optimizes. SEO setup. Local payment configuration. Blog templates. Email setup. Social templates. You provide input; we do the work.' }, { title: 'Launch (Day 7 Onward)', body: 'Website goes live. Google submission. Within 4 weeks, you\'re ranking for your keywords. Customers start finding you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Core features', 'Hosting + domain included', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'SEO optimization included', '1 blog/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blogs/month', 'Growth strategy expert', 'Monthly 1-on-1 review', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000 (complex setups)', items: ['Unlimited pages/products', 'E-commerce capability', '10 blogs/month', '20 social posts/month', 'Managed advertising', 'Dedicated team'] }],
    whyOver: [{ label: 'vs. Islamabad Agencies', items: ['They take weeks. We take 7 days.', 'They charge PKR 300,000+ setup. We charge PKR 22,500.', 'They charge per-change. We include unlimited changes.', 'Result: Faster, cheaper, owned by you.'] }, { label: 'vs. Global Platforms (Wix, Squarespace)', items: ['No local payment methods.', 'No Pakistan-based support.', 'No included marketing or growth team.', 'Result: Higher hidden costs, slower ranking.'] }, { label: 'vs. Self-Managed WordPress', items: ['WordPress complexity, maintenance, updates, plugin management.', 'We handle everything automatically.', 'We include SEO, email, social—WordPress requires separate tools.', 'Result: Simpler, lower total cost.'] }],
  },
  'jacobabad': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'jhang': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Payments. Templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, supported.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'jhelum': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Managed.'] }],
  },
  'kamoke': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'kandhkot': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'karachi': {
    process: [{ title: 'Discovery Call (Day 1)', body: 'We learn your business—what you sell, who your customers are, what makes you unique. 30-minute call. That\'s it.' }, { title: 'Build & Optimize (Days 2-7)', body: 'Our team designs, builds, and optimizes your website. SEO from day one. Local payment setup. Blog, email, social media templates ready. You don\'t touch anything—we handle it.' }, { title: 'Launch & Grow (Day 7+)', body: 'Your website goes live. We submit to Google. Within 2-4 weeks, you\'re ranking for your target keywords. Customers start finding you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Basic features', 'Hosting + domain included', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'Advanced SEO', '1 blog/month included', 'VIP phone support', 'Unlimited email accounts'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blogs/month', 'Dedicated marketing expert', '1-on-1 monthly session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000 (for complex setups)', items: ['Unlimited pages/products', 'Advanced e-commerce', '10 blogs/month', '20 social posts/month', 'Ad campaigns managed', 'Full team support', '25 email accounts'] }],
    whyOver: [{ label: 'vs. Local Agencies', items: ['Agencies take 4–8 weeks. We take 7 days.', 'Agencies charge PKR 200,000+ setup. We charge PKR 22,500.', 'Agencies charge per-change fees. We include unlimited changes.', 'Result: You save money, launch faster, own your platform completely.'] }, { label: 'vs. DIY Builders (Wix, Squarespace)', items: ['No local payment support (Wix, Squarespace require international gateways).', 'No included marketing team.', 'No support in Pakistan timezone.', 'Result: Higher costs, slower ranking, DIY marketing headache.'] }, { label: 'vs. WordPress', items: ['WordPress requires hosting + plugins + maintenance = PKR 15,000–25,000/month hidden costs.', 'We include everything in one fee.', 'WordPress needs developer for changes. We handle updates.', 'Result: Cleaner, simpler, cheaper.'] }],
  },
  'khairpur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'khanewal': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'khanpur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'khuzdar': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'kohat': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'kot-adu': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'lahore': {
    process: [{ title: 'Talk to Us (Day 1)', body: 'Tell us about your business. 30 minutes. We understand what you do, who your customers are, and what success looks like for you.' }, { title: 'We Build (Days 2-7)', body: 'Our team designs and builds. We optimize for SEO. Set up local payments. Prepare your blog, email, and social templates. You don\'t do the technical work—we do.' }, { title: 'Launch & Growth (Day 7+)', body: 'Your website goes live. We submit to Google Search Console. Within 4 weeks, you\'re ranking for your keywords. Customers start finding you.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Essential features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'Advanced SEO included', '1 blog post/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blog posts/month', 'Dedicated growth expert', 'Monthly 1-on-1 session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'E-commerce ready', '10 blog posts/month', '20 social posts/month', 'Managed ad campaigns', 'Full team support'] }],
    whyOver: [{ label: 'vs. Lahore Web Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Per-change fees. Us: Unlimited changes included.', 'Result: Faster, cheaper, you own it completely.'] }, { label: 'vs. Wix/Squarespace', items: ['No local payment support.', 'No local support team.', 'No included marketing or SEO.', 'Hidden app costs add up.', 'Result: More expensive in practice, slower ranking.'] }, { label: 'vs. WordPress', items: ['WordPress = DIY complexity (plugins, updates, security, maintenance).', 'We handle everything automatically.', 'WordPress looks cheap but costs more when you factor in plugins + developer time.', 'Result: Simpler, cheaper, faster results.'] }],
  },
  'larkana': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'mandi-bahauddin': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'mansehra': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'mardan': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'mianwali': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, affordable.'] }],
  },
  'mirpur-khas': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'multan': {
    process: [{ title: 'Consultation (Day 1)', body: 'Tell us about your business. 30 minutes. We learn your goals, customers, and vision for growth.' }, { title: 'We Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media preparation. All technical work handled by us.' }, { title: 'Launch & Grow (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Customers find you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Essential features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'SEO optimization built-in', '1 blog post/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blog posts/month', 'Dedicated growth consultant', 'Monthly 1-on-1 strategy session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'E-commerce ready', '10 blog posts/month', '20 social media posts/month', 'Managed ad campaigns', 'Full team support'] }],
    whyOver: [{ label: 'vs. Multan Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes.', 'Result: Faster, cheaper, you own it.'] }, { label: 'vs. Budget Platforms (Wix, Squarespace)', items: ['No local payment support.', 'No Pakistan-based support.', 'Hidden app costs accumulate.', 'No included marketing.', 'Result: Higher costs, slower ranking.'] }, { label: 'vs. WordPress (DIY)', items: ['WordPress: Complexity, maintenance, updates.', 'Us: Fully managed, automated.', 'WordPress: Hidden costs (plugins, tools) = PKR 15,000–25,000/month.', 'Us: One transparent fee.', 'Result: Simpler, cheaper, faster.'] }],
  },
  'muridke': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'murree': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'muzaffargarh': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'nawabshah': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'nowshera': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'okara': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO. Payments. Templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs, 20 social posts, managed ads)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['7 days, PKR 22,500, you own it.'] }, { label: 'vs. Global Platforms', items: ['Local support, local payments.'] }, { label: 'vs. WordPress', items: ['Managed, simple, affordable.'] }],
  },
  'pakpattan': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, complete ownership.'] }, { label: 'Platforms', items: ['Local support, local payments, no hidden costs.'] }, { label: 'WordPress', items: ['Fully managed, affordable, simple.'] }],
  },
  'peshawar': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We learn your goals, customers, and vision for growth.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media preparation. All technical work handled.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Customers find you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Core features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'SEO optimization included', '1 blog/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blogs/month', 'Dedicated growth expert', 'Monthly 1-on-1 session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'E-commerce ready', '10 blogs/month', '20 social posts/month', 'Managed ad campaigns', 'Full team support'] }],
    whyOver: [{ label: 'vs. Peshawar Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes.', 'Result: Faster, cheaper, you own it.'] }, { label: 'vs. Budget Platforms (Wix, Squarespace)', items: ['No local payment support.', 'No Pakistan-based support.', 'Hidden app costs.', 'No included marketing.', 'Result: Higher costs, slower ranking.'] }, { label: 'vs. WordPress (DIY)', items: ['WordPress: Complexity, maintenance, updates.', 'Us: Fully managed, automated.', 'WordPress: Hidden costs = PKR 15,000–25,000/month.', 'Us: One transparent fee.', 'Result: Simpler, cheaper, faster.'] }],
  },
  'quetta': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We learn your goals, customers, and growth vision.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media preparation. All technical work handled by us.' }, { title: 'Launch & Grow (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Customers find you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Essential features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'SEO optimization included', '1 blog/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blogs/month', 'Dedicated growth expert', 'Monthly 1-on-1 session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'E-commerce ready', '10 blogs/month', '20 social posts/month', 'Managed ad campaigns', 'Full team support'] }],
    whyOver: [{ label: 'vs. Quetta Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes.'] }, { label: 'vs. Budget Platforms', items: ['No local payments.', 'Hidden costs accumulate.', 'No local support.'] }, { label: 'vs. WordPress DIY', items: ['WordPress: Complexity, maintenance.', 'Us: Fully managed.', 'WordPress: PKR 15,000–25,000/month hidden costs.'] }],
  },
  'rahim-yar-khan': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We understand your goals and vision.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Payment integration. Blog templates. Email configuration. All technical work by us.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for keywords.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs/month, 20 social posts, managed ads)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['7 days, PKR 22,500, complete ownership.'] }, { label: 'vs. Global Platforms', items: ['Local support, local payments, no hidden costs.'] }, { label: 'vs. WordPress', items: ['Fully managed, affordable, simple.'] }],
  },
  'rawalpindi': {
    process: [{ title: 'Consultation (Day 1)', body: 'Tell us about your business. 30 minutes. We understand your goals, customers, and success metrics.' }, { title: 'We Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media preparation. We do all the technical work.' }, { title: 'Go Live (Day 7+)', body: 'Your website launches. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Customers find you organically.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Core website features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'Built-in SEO optimization', '1 blog post/month', 'Priority phone support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blog posts/month', 'Dedicated growth consultant', 'Monthly 1-on-1 strategy session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'Full e-commerce capability', '10 blog posts/month', '20 social media posts/month', 'Professional ad management', 'Complete team support'] }],
    whyOver: [{ label: 'vs. Rawalpindi Web Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes.', 'Agencies: You depend on them. Us: You own your website.'] }, { label: 'vs. Budget Platforms (Wix, Squarespace)', items: ['No local payment support.', 'Hidden app costs accumulate.', 'No Pakistan-based support team.', 'No included marketing or SEO.', 'Result: Higher actual costs, slower results.'] }, { label: 'vs. WordPress (DIY)', items: ['WordPress: Complex setup, maintenance burden.', 'Us: Fully managed, no technical knowledge needed.', 'WordPress: Plugins + tools = PKR 15,000+/month hidden costs.', 'Us: One transparent fee includes everything.'] }],
  },
  'sadiqabad': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, complete ownership.'] }, { label: 'Platforms', items: ['Local support, transparent.'] }, { label: 'WordPress', items: ['Fully managed, affordable.'] }],
  },
  'sahiwal': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Payments. Templates. All technical.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Google submission. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs, 20 social posts, managed ads)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Agencies', items: ['Faster (7 days), cheaper (PKR 22,500), complete ownership.'] }, { label: 'vs. Global Platforms', items: ['Local support, local payments, no hidden costs.'] }, { label: 'vs. WordPress DIY', items: ['Fully managed, affordable, simple.'] }],
  },
  'sargodha': {
    process: [{ title: 'Discovery (Day 1)', body: 'Talk to us. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Payments. Templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper.'] }, { label: 'Platforms', items: ['Local support.'] }, { label: 'WordPress', items: ['Simple, managed.'] }],
  },
  'sheikhupura': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We understand your goals and vision.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social templates. All technical work.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs/month, 20 social posts, managed ads, full team)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'vs. Sheikhupura Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited changes included.', 'Result: Faster, cheaper, complete ownership.'] }, { label: 'vs. Global Platforms (Wix, Squarespace)', items: ['No local payment methods.', 'No Pakistan-based support.', 'Hidden app costs accumulate.', 'No included marketing strategy.', 'Result: Higher costs, slower ranking.'] }, { label: 'vs. WordPress (Self-Managed)', items: ['WordPress: Complex maintenance and updates.', 'Us: Fully managed and automated.', 'WordPress: PKR 15,000–25,000/month hidden costs.', 'Us: One transparent, all-inclusive fee.', 'Result: Simpler, cheaper, faster results.'] }],
  },
  'shikarpur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'sialkot': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes. We understand your goals, customers, and growth vision.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Local payment integration. Blog templates. Email configuration. Social media templates. All technical work by us.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. We submit to Google. Within 4 weeks, you\'re ranking for your keywords. Organic customers start flowing.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: ['5–10 pages', 'Core features', 'Hosting + domain', '5 email accounts'] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: ['30 pages', 'SEO optimization', '1 blog/month', 'Priority support', 'Unlimited email'] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: ['50 pages', '3 blogs/month', 'Dedicated growth expert', 'Monthly 1-on-1 session', '15 email accounts'] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: ['Unlimited pages/products', 'E-commerce capability', '10 blogs/month', '20 social posts/month', 'Managed advertising', 'Full team support'] }],
    whyOver: [{ label: 'vs. Sialkot Agencies', items: ['Agencies: 4–8 weeks. Us: 7 days.', 'Agencies: PKR 300,000+ setup. Us: PKR 22,500.', 'Agencies: Charge per change. Us: Unlimited.'] }, { label: 'vs. Global Platforms', items: ['No local payment support.', 'No local support team.', 'Hidden app costs.'] }, { label: 'vs. WordPress', items: ['WordPress: Complex, maintenance burden.', 'Us: Fully managed, automated.', 'WordPress: PKR 15,000–25,000/month hidden costs.'] }],
  },
  'sukkur': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO setup. Payments. Templates.' }, { title: 'Launch (Day 7+)', body: 'Your website goes live. Within 4 weeks, you\'re ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local support, no hidden costs.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'swabi': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'tando-allahyar': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'vehari': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'wah-cantonment': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business. 30 minutes.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO. Payments. Templates. All technical.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month (5–10 pages, hosting, domain, 5 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month (30 pages, SEO, 1 blog/month, unlimited email)', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month (50 pages, 3 blogs/month, dedicated expert, 15 emails)', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month (unlimited pages/products, e-commerce, 10 blogs, 20 social posts, ads)', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['Faster, cheaper, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
  'zhob': {
    process: [{ title: 'Discovery (Day 1)', body: 'Tell us about your business.' }, { title: 'Build (Days 2-7)', body: 'Our team designs and builds. SEO, payments, templates.' }, { title: 'Launch (Day 7+)', body: 'Website goes live. Within 4 weeks, ranking.' }],
    plans: [{ name: 'Launch', price: 'PKR 4,500/month', setup: 'PKR 22,500', items: [] }, { name: 'Boost', price: 'PKR 15,600/month', setup: 'PKR 22,500', items: [] }, { name: 'Growth', price: 'PKR 27,000/month', setup: 'PKR 22,500', items: [] }, { name: 'Platinum', price: 'PKR 55,000/month', setup: 'PKR 140,000', items: [] }],
    whyOver: [{ label: 'Agencies', items: ['7 days, PKR 22,500, yours.'] }, { label: 'Platforms', items: ['Local, transparent.'] }, { label: 'WordPress', items: ['Managed, simple.'] }],
  },
}
